// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package plugin

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	billinggroup "github.com/aiven/terraform-provider-aiven/internal/plugin/service/billinggroup"
	byocawsentity "github.com/aiven/terraform-provider-aiven/internal/plugin/service/byoc/aws_entity"
	byocawsprovision "github.com/aiven/terraform-provider-aiven/internal/plugin/service/byoc/aws_provision"
	byocpermissions "github.com/aiven/terraform-provider-aiven/internal/plugin/service/byoc/permissions"
	clickhousedatabase "github.com/aiven/terraform-provider-aiven/internal/plugin/service/clickhouse/database"
	clickhouseuser "github.com/aiven/terraform-provider-aiven/internal/plugin/service/clickhouse/user"
	cmk "github.com/aiven/terraform-provider-aiven/internal/plugin/service/cmk"
	cmkaccessoraws "github.com/aiven/terraform-provider-aiven/internal/plugin/service/cmk/accessor/aws"
	cmkaccessorazure "github.com/aiven/terraform-provider-aiven/internal/plugin/service/cmk/accessor/azure"
	cmkaccessorgcp "github.com/aiven/terraform-provider-aiven/internal/plugin/service/cmk/accessor/gcp"
	cmkaccessoroci "github.com/aiven/terraform-provider-aiven/internal/plugin/service/cmk/accessor/oci"
	flinkapplication "github.com/aiven/terraform-provider-aiven/internal/plugin/service/flink/application"
	flinkapplicationdeployment "github.com/aiven/terraform-provider-aiven/internal/plugin/service/flink/deployment"
	flinkjarapplication "github.com/aiven/terraform-provider-aiven/internal/plugin/service/flink/jarapplication"
	flinkjarapplicationdeployment "github.com/aiven/terraform-provider-aiven/internal/plugin/service/flink/jardeployment"
	flinkjarapplicationversion "github.com/aiven/terraform-provider-aiven/internal/plugin/service/flink/jarversion"
	governanceaccess "github.com/aiven/terraform-provider-aiven/internal/plugin/service/governance/access"
	kafkaacl "github.com/aiven/terraform-provider-aiven/internal/plugin/service/kafka/acl"
	mirrormakerreplicationflow "github.com/aiven/terraform-provider-aiven/internal/plugin/service/kafka/mirrormakerreplicationflow"
	kafkanativeacl "github.com/aiven/terraform-provider-aiven/internal/plugin/service/kafka/nativeacl"
	kafkatopic "github.com/aiven/terraform-provider-aiven/internal/plugin/service/kafka/topic"
	kafkatopiclist "github.com/aiven/terraform-provider-aiven/internal/plugin/service/kafka/topiclist"
	kafkauser "github.com/aiven/terraform-provider-aiven/internal/plugin/service/kafka/user"
	kafkaschemaregistryacl "github.com/aiven/terraform-provider-aiven/internal/plugin/service/kafkaschema/registryacl"
	mysqldatabase "github.com/aiven/terraform-provider-aiven/internal/plugin/service/mysql/database"
	mysqluser "github.com/aiven/terraform-provider-aiven/internal/plugin/service/mysql/user"
	opensearchsecuritypluginconfig "github.com/aiven/terraform-provider-aiven/internal/plugin/service/opensearch/securitypluginconfig"
	opensearchuser "github.com/aiven/terraform-provider-aiven/internal/plugin/service/opensearch/user"
	organizationaddress "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/address"
	organizationapplicationuser "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/applicationuser"
	organizationapplicationusertoken "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/applicationusertoken"
	organizationbillinggroup "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/billinggroup"
	organizationbillinggrouplist "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/billinggrouplist"
	organizationpaymentmethodlist "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/paymentmethodlist"
	organizationproject "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/project"
	organizationalunit "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/unit"
	organizationusergroup "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/usergroup"
	organizationusergrouplist "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/usergrouplist"
	organizationusergroupmember "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/usergroupmember"
	organizationusergroupmemberlist "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/usergroupmemberlist"
	organizationuserlist "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/userlist"
	connectionpool "github.com/aiven/terraform-provider-aiven/internal/plugin/service/pg/connectionpool"
	pgdatabase "github.com/aiven/terraform-provider-aiven/internal/plugin/service/pg/database"
	pguser "github.com/aiven/terraform-provider-aiven/internal/plugin/service/pg/user"
	serviceplan "github.com/aiven/terraform-provider-aiven/internal/plugin/service/plan"
	serviceplanlist "github.com/aiven/terraform-provider-aiven/internal/plugin/service/planlist"
	servicelist "github.com/aiven/terraform-provider-aiven/internal/plugin/service/servicelist"
	staticip "github.com/aiven/terraform-provider-aiven/internal/plugin/service/staticip"
	upgradestep "github.com/aiven/terraform-provider-aiven/internal/plugin/service/upgradepipeline/step"
	valkeyuser "github.com/aiven/terraform-provider-aiven/internal/plugin/service/valkey/user"
	awsorgvpcpeeringconnection "github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/awsorgvpcpeeringconnection"
	awsprivatelink "github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/awsprivatelink"
	azureorgvpcpeeringconnection "github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/azureorgvpcpeeringconnection"
	azureprivatelink "github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/azureprivatelink"
	gcporgvpcpeeringconnection "github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/gcporgvpcpeeringconnection"
	gcpprivatelink "github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/gcpprivatelink"
	organizationvpc "github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/organizationvpc"
	projectvpc "github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/projectvpc"
	transitgatewayvpcattachment "github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/transitgatewayvpcattachment"
)

func Resources() map[string]func() resource.Resource {
	return map[string]func() resource.Resource{
		"aiven_aws_org_vpc_peering_connection":      adapter.NewLazyResource(awsorgvpcpeeringconnection.ResourceOptions),
		"aiven_aws_privatelink":                     adapter.NewLazyResource(awsprivatelink.ResourceOptions),
		"aiven_azure_org_vpc_peering_connection":    adapter.NewLazyResource(azureorgvpcpeeringconnection.ResourceOptions),
		"aiven_azure_privatelink":                   adapter.NewLazyResource(azureprivatelink.ResourceOptions),
		"aiven_billing_group":                       adapter.NewLazyResource(billinggroup.ResourceOptions),
		"aiven_byoc_aws_entity":                     adapter.NewLazyResource(byocawsentity.ResourceOptions),
		"aiven_byoc_aws_provision":                  adapter.NewLazyResource(byocawsprovision.ResourceOptions),
		"aiven_byoc_permissions":                    adapter.NewLazyResource(byocpermissions.ResourceOptions),
		"aiven_clickhouse_database":                 adapter.NewLazyResource(clickhousedatabase.ResourceOptions),
		"aiven_clickhouse_user":                     adapter.NewLazyResource(clickhouseuser.ResourceOptions),
		"aiven_cmk":                                 adapter.NewLazyResource(cmk.ResourceOptions),
		"aiven_connection_pool":                     adapter.NewLazyResource(connectionpool.ResourceOptions),
		"aiven_flink_application":                   adapter.NewLazyResource(flinkapplication.ResourceOptions),
		"aiven_flink_application_deployment":        adapter.NewLazyResource(flinkapplicationdeployment.ResourceOptions),
		"aiven_flink_jar_application":               adapter.NewLazyResource(flinkjarapplication.ResourceOptions),
		"aiven_flink_jar_application_deployment":    adapter.NewLazyResource(flinkjarapplicationdeployment.ResourceOptions),
		"aiven_flink_jar_application_version":       adapter.NewLazyResource(flinkjarapplicationversion.ResourceOptions),
		"aiven_gcp_org_vpc_peering_connection":      adapter.NewLazyResource(gcporgvpcpeeringconnection.ResourceOptions),
		"aiven_gcp_privatelink":                     adapter.NewLazyResource(gcpprivatelink.ResourceOptions),
		"aiven_governance_access":                   adapter.NewLazyResource(governanceaccess.ResourceOptions),
		"aiven_kafka_acl":                           adapter.NewLazyResource(kafkaacl.ResourceOptions),
		"aiven_kafka_native_acl":                    adapter.NewLazyResource(kafkanativeacl.ResourceOptions),
		"aiven_kafka_schema_registry_acl":           adapter.NewLazyResource(kafkaschemaregistryacl.ResourceOptions),
		"aiven_kafka_topic":                         adapter.NewLazyResource(kafkatopic.ResourceOptions),
		"aiven_kafka_user":                          adapter.NewLazyResource(kafkauser.ResourceOptions),
		"aiven_mirrormaker_replication_flow":        adapter.NewLazyResource(mirrormakerreplicationflow.ResourceOptions),
		"aiven_mysql_database":                      adapter.NewLazyResource(mysqldatabase.ResourceOptions),
		"aiven_mysql_user":                          adapter.NewLazyResource(mysqluser.ResourceOptions),
		"aiven_opensearch_security_plugin_config":   adapter.NewLazyResource(opensearchsecuritypluginconfig.ResourceOptions),
		"aiven_opensearch_user":                     adapter.NewLazyResource(opensearchuser.ResourceOptions),
		"aiven_organization_address":                adapter.NewLazyResource(organizationaddress.ResourceOptions),
		"aiven_organization_application_user":       adapter.NewLazyResource(organizationapplicationuser.ResourceOptions),
		"aiven_organization_application_user_token": adapter.NewLazyResource(organizationapplicationusertoken.ResourceOptions),
		"aiven_organization_billing_group":          adapter.NewLazyResource(organizationbillinggroup.ResourceOptions),
		"aiven_organization_project":                adapter.NewLazyResource(organizationproject.ResourceOptions),
		"aiven_organization_user_group":             adapter.NewLazyResource(organizationusergroup.ResourceOptions),
		"aiven_organization_user_group_member":      adapter.NewLazyResource(organizationusergroupmember.ResourceOptions),
		"aiven_organization_vpc":                    adapter.NewLazyResource(organizationvpc.ResourceOptions),
		"aiven_organizational_unit":                 adapter.NewLazyResource(organizationalunit.ResourceOptions),
		"aiven_pg_database":                         adapter.NewLazyResource(pgdatabase.ResourceOptions),
		"aiven_pg_user":                             adapter.NewLazyResource(pguser.ResourceOptions),
		"aiven_project_vpc":                         adapter.NewLazyResource(projectvpc.ResourceOptions),
		"aiven_static_ip":                           adapter.NewLazyResource(staticip.ResourceOptions),
		"aiven_transit_gateway_vpc_attachment":      adapter.NewLazyResource(transitgatewayvpcattachment.ResourceOptions),
		"aiven_upgrade_step":                        adapter.NewLazyResource(upgradestep.ResourceOptions),
		"aiven_valkey_user":                         adapter.NewLazyResource(valkeyuser.ResourceOptions),
	}
}

func DataSources() map[string]func() datasource.DataSource {
	return map[string]func() datasource.DataSource{
		"aiven_aws_org_vpc_peering_connection":      adapter.NewLazyDataSource(awsorgvpcpeeringconnection.DataSourceOptions),
		"aiven_aws_privatelink":                     adapter.NewLazyDataSource(awsprivatelink.DataSourceOptions),
		"aiven_azure_org_vpc_peering_connection":    adapter.NewLazyDataSource(azureorgvpcpeeringconnection.DataSourceOptions),
		"aiven_azure_privatelink":                   adapter.NewLazyDataSource(azureprivatelink.DataSourceOptions),
		"aiven_billing_group":                       adapter.NewLazyDataSource(billinggroup.DataSourceOptions),
		"aiven_clickhouse_database":                 adapter.NewLazyDataSource(clickhousedatabase.DataSourceOptions),
		"aiven_clickhouse_user":                     adapter.NewLazyDataSource(clickhouseuser.DataSourceOptions),
		"aiven_cmk_accessor_aws":                    adapter.NewLazyDataSource(cmkaccessoraws.DataSourceOptions),
		"aiven_cmk_accessor_azure":                  adapter.NewLazyDataSource(cmkaccessorazure.DataSourceOptions),
		"aiven_cmk_accessor_gcp":                    adapter.NewLazyDataSource(cmkaccessorgcp.DataSourceOptions),
		"aiven_cmk_accessor_oci":                    adapter.NewLazyDataSource(cmkaccessoroci.DataSourceOptions),
		"aiven_connection_pool":                     adapter.NewLazyDataSource(connectionpool.DataSourceOptions),
		"aiven_flink_application":                   adapter.NewLazyDataSource(flinkapplication.DataSourceOptions),
		"aiven_gcp_org_vpc_peering_connection":      adapter.NewLazyDataSource(gcporgvpcpeeringconnection.DataSourceOptions),
		"aiven_gcp_privatelink":                     adapter.NewLazyDataSource(gcpprivatelink.DataSourceOptions),
		"aiven_kafka_acl":                           adapter.NewLazyDataSource(kafkaacl.DataSourceOptions),
		"aiven_kafka_schema_registry_acl":           adapter.NewLazyDataSource(kafkaschemaregistryacl.DataSourceOptions),
		"aiven_kafka_topic":                         adapter.NewLazyDataSource(kafkatopic.DataSourceOptions),
		"aiven_kafka_topic_list":                    adapter.NewLazyDataSource(kafkatopiclist.DataSourceOptions),
		"aiven_kafka_user":                          adapter.NewLazyDataSource(kafkauser.DataSourceOptions),
		"aiven_mirrormaker_replication_flow":        adapter.NewLazyDataSource(mirrormakerreplicationflow.DataSourceOptions),
		"aiven_mysql_database":                      adapter.NewLazyDataSource(mysqldatabase.DataSourceOptions),
		"aiven_mysql_user":                          adapter.NewLazyDataSource(mysqluser.DataSourceOptions),
		"aiven_opensearch_security_plugin_config":   adapter.NewLazyDataSource(opensearchsecuritypluginconfig.DataSourceOptions),
		"aiven_opensearch_user":                     adapter.NewLazyDataSource(opensearchuser.DataSourceOptions),
		"aiven_organization_address":                adapter.NewLazyDataSource(organizationaddress.DataSourceOptions),
		"aiven_organization_application_user":       adapter.NewLazyDataSource(organizationapplicationuser.DataSourceOptions),
		"aiven_organization_billing_group":          adapter.NewLazyDataSource(organizationbillinggroup.DataSourceOptions),
		"aiven_organization_billing_group_list":     adapter.NewLazyDataSource(organizationbillinggrouplist.DataSourceOptions),
		"aiven_organization_payment_method_list":    adapter.NewLazyDataSource(organizationpaymentmethodlist.DataSourceOptions),
		"aiven_organization_project":                adapter.NewLazyDataSource(organizationproject.DataSourceOptions),
		"aiven_organization_user_group":             adapter.NewLazyDataSource(organizationusergroup.DataSourceOptions),
		"aiven_organization_user_group_list":        adapter.NewLazyDataSource(organizationusergrouplist.DataSourceOptions),
		"aiven_organization_user_group_member_list": adapter.NewLazyDataSource(organizationusergroupmemberlist.DataSourceOptions),
		"aiven_organization_user_list":              adapter.NewLazyDataSource(organizationuserlist.DataSourceOptions),
		"aiven_organization_vpc":                    adapter.NewLazyDataSource(organizationvpc.DataSourceOptions),
		"aiven_organizational_unit":                 adapter.NewLazyDataSource(organizationalunit.DataSourceOptions),
		"aiven_pg_database":                         adapter.NewLazyDataSource(pgdatabase.DataSourceOptions),
		"aiven_pg_user":                             adapter.NewLazyDataSource(pguser.DataSourceOptions),
		"aiven_project_vpc":                         adapter.NewLazyDataSource(projectvpc.DataSourceOptions),
		"aiven_service_list":                        adapter.NewLazyDataSource(servicelist.DataSourceOptions),
		"aiven_service_plan":                        adapter.NewLazyDataSource(serviceplan.DataSourceOptions),
		"aiven_service_plan_list":                   adapter.NewLazyDataSource(serviceplanlist.DataSourceOptions),
		"aiven_transit_gateway_vpc_attachment":      adapter.NewLazyDataSource(transitgatewayvpcattachment.DataSourceOptions),
		"aiven_valkey_user":                         adapter.NewLazyDataSource(valkeyuser.DataSourceOptions),
	}
}
