// Copyright (c) 2025 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package plugin

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/address"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/applicationuser"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/applicationusertoken"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/billinggroup"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/billinggrouplist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/project"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/usergrouplist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/usergroupmember"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/userlist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/plan"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/planlist"
)

func Resources() map[string]func() resource.Resource {
	return map[string]func() resource.Resource{
		"aiven_organization_address":                adapter.NewLazyResource(address.ResourceOptions),
		"aiven_organization_application_user":       adapter.NewLazyResource(applicationuser.ResourceOptions),
		"aiven_organization_application_user_token": adapter.NewLazyResource(applicationusertoken.ResourceOptions),
		"aiven_organization_billing_group":          adapter.NewLazyResource(billinggroup.ResourceOptions),
		"aiven_organization_project":                adapter.NewLazyResource(project.ResourceOptions),
		"aiven_organization_user_group_member":      adapter.NewLazyResource(usergroupmember.ResourceOptions),
	}
}

func DataSources() map[string]func() datasource.DataSource {
	return map[string]func() datasource.DataSource{
		"aiven_organization_address":            adapter.NewLazyDataSource(address.DataSourceOptions),
		"aiven_organization_application_user":   adapter.NewLazyDataSource(applicationuser.DataSourceOptions),
		"aiven_organization_billing_group":      adapter.NewLazyDataSource(billinggroup.DataSourceOptions),
		"aiven_organization_billing_group_list": adapter.NewLazyDataSource(billinggrouplist.DataSourceOptions),
		"aiven_organization_project":            adapter.NewLazyDataSource(project.DataSourceOptions),
		"aiven_organization_user_group_list":    adapter.NewLazyDataSource(usergrouplist.DataSourceOptions),
		"aiven_organization_user_list":          adapter.NewLazyDataSource(userlist.DataSourceOptions),
		"aiven_service_plan":                    adapter.NewLazyDataSource(plan.DataSourceOptions),
		"aiven_service_plan_list":               adapter.NewLazyDataSource(planlist.DataSourceOptions),
	}
}
