// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package plugin

import (
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/billinggroup"
	awsentity "github.com/aiven/terraform-provider-aiven/internal/plugin/service/byoc/aws_entity"
	awsprovision "github.com/aiven/terraform-provider-aiven/internal/plugin/service/byoc/aws_provision"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/byoc/permissions"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/clickhouse/database"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/clickhouse/user"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/cmk"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/flink/application"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/flink/deployment"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/governance/access"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/kafka/topiclist"
	database1 "github.com/aiven/terraform-provider-aiven/internal/plugin/service/mysql/database"
	user1 "github.com/aiven/terraform-provider-aiven/internal/plugin/service/mysql/user"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/opensearch/securitypluginconfig"
	user2 "github.com/aiven/terraform-provider-aiven/internal/plugin/service/opensearch/user"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/address"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/applicationuser"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/applicationusertoken"
	billinggroup1 "github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/billinggroup"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/billinggrouplist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/paymentmethodlist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/project"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/unit"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/usergrouplist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/usergroupmember"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/usergroupmemberlist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/organization/userlist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/pg/connectionpool"
	database2 "github.com/aiven/terraform-provider-aiven/internal/plugin/service/pg/database"
	user3 "github.com/aiven/terraform-provider-aiven/internal/plugin/service/pg/user"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/plan"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/planlist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/servicelist"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/staticip"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/service/vpc/projectvpc"
)

func Resources() map[string]func() resource.Resource {
	return map[string]func() resource.Resource{
		"aiven_billing_group":                       adapter.NewLazyResource(billinggroup.ResourceOptions),
		"aiven_byoc_aws_entity":                     adapter.NewLazyResource(awsentity.ResourceOptions),
		"aiven_byoc_aws_provision":                  adapter.NewLazyResource(awsprovision.ResourceOptions),
		"aiven_byoc_permissions":                    adapter.NewLazyResource(permissions.ResourceOptions),
		"aiven_clickhouse_database":                 adapter.NewLazyResource(database.ResourceOptions),
		"aiven_clickhouse_user":                     adapter.NewLazyResource(user.ResourceOptions),
		"aiven_cmk":                                 adapter.NewLazyResource(cmk.ResourceOptions),
		"aiven_connection_pool":                     adapter.NewLazyResource(connectionpool.ResourceOptions),
		"aiven_flink_application":                   adapter.NewLazyResource(application.ResourceOptions),
		"aiven_flink_application_deployment":        adapter.NewLazyResource(deployment.ResourceOptions),
		"aiven_governance_access":                   adapter.NewLazyResource(access.ResourceOptions),
		"aiven_mysql_database":                      adapter.NewLazyResource(database1.ResourceOptions),
		"aiven_mysql_user":                          adapter.NewLazyResource(user1.ResourceOptions),
		"aiven_opensearch_security_plugin_config":   adapter.NewLazyResource(securitypluginconfig.ResourceOptions),
		"aiven_opensearch_user":                     adapter.NewLazyResource(user2.ResourceOptions),
		"aiven_organization_address":                adapter.NewLazyResource(address.ResourceOptions),
		"aiven_organization_application_user":       adapter.NewLazyResource(applicationuser.ResourceOptions),
		"aiven_organization_application_user_token": adapter.NewLazyResource(applicationusertoken.ResourceOptions),
		"aiven_organization_billing_group":          adapter.NewLazyResource(billinggroup1.ResourceOptions),
		"aiven_organization_project":                adapter.NewLazyResource(project.ResourceOptions),
		"aiven_organization_user_group_member":      adapter.NewLazyResource(usergroupmember.ResourceOptions),
		"aiven_organizational_unit":                 adapter.NewLazyResource(unit.ResourceOptions),
		"aiven_pg_database":                         adapter.NewLazyResource(database2.ResourceOptions),
		"aiven_pg_user":                             adapter.NewLazyResource(user3.ResourceOptions),
		"aiven_project_vpc":                         adapter.NewLazyResource(projectvpc.ResourceOptions),
		"aiven_static_ip":                           adapter.NewLazyResource(staticip.ResourceOptions),
	}
}

func DataSources() map[string]func() datasource.DataSource {
	return map[string]func() datasource.DataSource{
		"aiven_billing_group":                       adapter.NewLazyDataSource(billinggroup.DataSourceOptions),
		"aiven_clickhouse_database":                 adapter.NewLazyDataSource(database.DataSourceOptions),
		"aiven_clickhouse_user":                     adapter.NewLazyDataSource(user.DataSourceOptions),
		"aiven_connection_pool":                     adapter.NewLazyDataSource(connectionpool.DataSourceOptions),
		"aiven_flink_application":                   adapter.NewLazyDataSource(application.DataSourceOptions),
		"aiven_kafka_topic_list":                    adapter.NewLazyDataSource(topiclist.DataSourceOptions),
		"aiven_mysql_database":                      adapter.NewLazyDataSource(database1.DataSourceOptions),
		"aiven_mysql_user":                          adapter.NewLazyDataSource(user1.DataSourceOptions),
		"aiven_opensearch_security_plugin_config":   adapter.NewLazyDataSource(securitypluginconfig.DataSourceOptions),
		"aiven_opensearch_user":                     adapter.NewLazyDataSource(user2.DataSourceOptions),
		"aiven_organization_address":                adapter.NewLazyDataSource(address.DataSourceOptions),
		"aiven_organization_application_user":       adapter.NewLazyDataSource(applicationuser.DataSourceOptions),
		"aiven_organization_billing_group":          adapter.NewLazyDataSource(billinggroup1.DataSourceOptions),
		"aiven_organization_billing_group_list":     adapter.NewLazyDataSource(billinggrouplist.DataSourceOptions),
		"aiven_organization_payment_method_list":    adapter.NewLazyDataSource(paymentmethodlist.DataSourceOptions),
		"aiven_organization_project":                adapter.NewLazyDataSource(project.DataSourceOptions),
		"aiven_organization_user_group_list":        adapter.NewLazyDataSource(usergrouplist.DataSourceOptions),
		"aiven_organization_user_group_member_list": adapter.NewLazyDataSource(usergroupmemberlist.DataSourceOptions),
		"aiven_organization_user_list":              adapter.NewLazyDataSource(userlist.DataSourceOptions),
		"aiven_organizational_unit":                 adapter.NewLazyDataSource(unit.DataSourceOptions),
		"aiven_pg_database":                         adapter.NewLazyDataSource(database2.DataSourceOptions),
		"aiven_pg_user":                             adapter.NewLazyDataSource(user3.DataSourceOptions),
		"aiven_service_list":                        adapter.NewLazyDataSource(servicelist.DataSourceOptions),
		"aiven_service_plan":                        adapter.NewLazyDataSource(plan.DataSourceOptions),
		"aiven_service_plan_list":                   adapter.NewLazyDataSource(planlist.DataSourceOptions),
	}
}
