// Copyright (c) 2025 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package billinggrouplist

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/util"
)

func idFields() []string {
	return []string{"organization_id"}
}

// dataModel Lists billing groups for an organization.
type dataModel struct {
	ID             types.String `tfsdk:"id"`
	BillingGroups  types.Set    `tfsdk:"billing_groups"`
	OrganizationID types.String `tfsdk:"organization_id"`
}

// dataBillingGroups
type dataBillingGroups struct {
	BillingAddressID     types.String `tfsdk:"billing_address_id"`
	BillingContactEmails types.Set    `tfsdk:"billing_contact_emails"`
	BillingCurrency      types.String `tfsdk:"billing_currency"`
	BillingEmails        types.Set    `tfsdk:"billing_emails"`
	BillingGroupID       types.String `tfsdk:"billing_group_id"`
	BillingGroupName     types.String `tfsdk:"billing_group_name"`
	CustomInvoiceText    types.String `tfsdk:"custom_invoice_text"`
	OrganizationID       types.String `tfsdk:"organization_id"`
	PaymentMethodID      types.String `tfsdk:"payment_method_id"`
	ShippingAddressID    types.String `tfsdk:"shipping_address_id"`
	VatID                types.String `tfsdk:"vat_id"`
}

type dtoModel struct {
	BillingGroups  *[]*dtoBillingGroups `json:"billing_groups,omitempty"`
	OrganizationID *string              `json:"organization_id,omitempty"`
}

type dtoBillingGroups struct {
	BillingAddressID     *string   `json:"billing_address_id,omitempty"`
	BillingContactEmails *[]string `json:"billing_contact_emails,omitempty"`
	BillingCurrency      *string   `json:"billing_currency,omitempty"`
	BillingEmails        *[]string `json:"billing_emails,omitempty"`
	BillingGroupID       *string   `json:"billing_group_id,omitempty"`
	BillingGroupName     *string   `json:"billing_group_name,omitempty"`
	CustomInvoiceText    *string   `json:"custom_invoice_text,omitempty"`
	OrganizationID       *string   `json:"organization_id,omitempty"`
	PaymentMethodID      *string   `json:"payment_method_id,omitempty"`
	ShippingAddressID    *string   `json:"shipping_address_id,omitempty"`
	VatID                *string   `json:"vat_id,omitempty"`
}

// flattenData turns Response into TF object
func flattenData[R any](ctx context.Context, data *dataModel, rsp *R, modifiers ...util.MapModifier[R]) diag.Diagnostics {
	dto := new(dtoModel)
	err := util.Unmarshal(rsp, dto, modifiers...)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("Unmarshal error", fmt.Sprintf("Failed to unmarshal Response to dtoModel: %s", err.Error()))
		return diags
	}
	if dto.BillingGroups != nil {
		vBillingGroups, diags := util.FlattenSetNested(ctx, flattenBillingGroups, *dto.BillingGroups, attrsBillingGroups())
		if diags.HasError() {
			return diags
		}
		data.BillingGroups = vBillingGroups
	}
	if dto.OrganizationID != nil {
		data.OrganizationID = types.StringPointerValue(dto.OrganizationID)
	}
	// Response may not contain ID fields.
	// In that case, `terraform import` won't be able to set them. Gets values from the ID.
	if data.ID.ValueString() != "" {
		var parts [1]string
		for i, v := range strings.SplitN(data.ID.ValueString(), "/", 1) {
			parts[i] = v
		}
		if data.OrganizationID.ValueString() == "" {
			data.OrganizationID = types.StringValue(parts[0])
		}
	}
	data.ID = types.StringValue(fmt.Sprintf("%s", data.OrganizationID.ValueString()))
	return nil
}

func flattenBillingGroups(ctx context.Context, dto *dtoBillingGroups) (*dataBillingGroups, diag.Diagnostics) {
	data := new(dataBillingGroups)
	if dto.BillingContactEmails != nil {
		vBillingContactEmails, diags := types.SetValueFrom(ctx, types.StringType, dto.BillingContactEmails)
		if diags.HasError() {
			return nil, diags
		}
		data.BillingContactEmails = vBillingContactEmails
	}
	if dto.BillingEmails != nil {
		vBillingEmails, diags := types.SetValueFrom(ctx, types.StringType, dto.BillingEmails)
		if diags.HasError() {
			return nil, diags
		}
		data.BillingEmails = vBillingEmails
	}
	if dto.BillingAddressID != nil {
		data.BillingAddressID = types.StringPointerValue(dto.BillingAddressID)
	}
	if dto.BillingCurrency != nil {
		data.BillingCurrency = types.StringPointerValue(dto.BillingCurrency)
	}
	if dto.BillingGroupID != nil {
		data.BillingGroupID = types.StringPointerValue(dto.BillingGroupID)
	}
	if dto.BillingGroupName != nil {
		data.BillingGroupName = types.StringPointerValue(dto.BillingGroupName)
	}
	if dto.CustomInvoiceText != nil {
		data.CustomInvoiceText = types.StringPointerValue(dto.CustomInvoiceText)
	}
	if dto.OrganizationID != nil {
		data.OrganizationID = types.StringPointerValue(dto.OrganizationID)
	}
	if dto.PaymentMethodID != nil {
		data.PaymentMethodID = types.StringPointerValue(dto.PaymentMethodID)
	}
	if dto.ShippingAddressID != nil {
		data.ShippingAddressID = types.StringPointerValue(dto.ShippingAddressID)
	}
	if dto.VatID != nil {
		data.VatID = types.StringPointerValue(dto.VatID)
	}
	return data, nil
}

func attrsBillingGroups() types.ObjectType {
	return types.ObjectType{AttrTypes: map[string]attr.Type{
		"billing_address_id":     types.StringType,
		"billing_contact_emails": types.SetType{ElemType: types.StringType},
		"billing_currency":       types.StringType,
		"billing_emails":         types.SetType{ElemType: types.StringType},
		"billing_group_id":       types.StringType,
		"billing_group_name":     types.StringType,
		"custom_invoice_text":    types.StringType,
		"organization_id":        types.StringType,
		"payment_method_id":      types.StringType,
		"shipping_address_id":    types.StringType,
		"vat_id":                 types.StringType,
	}}
}
