// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package billinggrouplist

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/hashicorp/terraform-plugin-framework/diag"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/errmsg"
)

var DataSourceOptions = adapter.DataSourceOptions[*datasourceModel, tfModel]{
	Beta:     true,
	Read:     readView,
	Schema:   datasourceSchema,
	TypeName: typeName,
}

func readView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		rsp, err := client.OrganizationBillingGroupList(ctx, state.OrganizationID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationBillingGroupList Error", err))
			return
		}
		diags.Append(flattenData(ctx, state, &map[string]any{"billing_groups": rsp}, flattenModifier(ctx, client))...)
	}()
	return diags
}
