// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package permissions

import (
	"context"
	"fmt"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/util"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"path/filepath"
	"strings"
)

const typeName = "aiven_byoc_permissions"

type tfModel struct {
	ID                       types.String `tfsdk:"id"`
	Accounts                 types.Set    `tfsdk:"accounts"`
	CustomCloudEnvironmentID types.String `tfsdk:"custom_cloud_environment_id"`
	OrganizationID           types.String `tfsdk:"organization_id"`
	ProjectNames             types.Set    `tfsdk:"project_names"`
}

func (tf *tfModel) SetID(vOrganizationID string, vCustomCloudEnvironmentID string) {
	tf.OrganizationID = types.StringValue(vOrganizationID)
	tf.CustomCloudEnvironmentID = types.StringValue(vCustomCloudEnvironmentID)
	tf.ID = types.StringValue(filepath.Join(vOrganizationID, vCustomCloudEnvironmentID))
}

type apiModel struct {
	Accounts                 *[]string `json:"accounts,omitempty"`
	CustomCloudEnvironmentID *string   `json:"custom_cloud_environment_id,omitempty"`
	OrganizationID           *string   `json:"organization_id,omitempty"`
	ProjectNames             *[]string `json:"projects,omitempty"`
}

// idFields the ID attribute fields, i.e.:
// terraform import aiven_byoc_permissions.foo ORGANIZATION_ID/CUSTOM_CLOUD_ENVIRONMENT_ID
func idFields() []string {
	return []string{"organization_id", "custom_cloud_environment_id"}
}

// expandData turns TF object into Request
func expandData[R any](ctx context.Context, plan, state *tfModel, req *R, modifiers ...util.MapModifier[tfModel]) diag.Diagnostics {
	api := new(apiModel)
	if !plan.Accounts.IsNull() || state != nil && !state.Accounts.IsNull() {
		vAccounts := make([]string, 0)
		diags := plan.Accounts.ElementsAs(ctx, &vAccounts, false)
		if diags.HasError() {
			return diags
		}
		api.Accounts = &vAccounts
	}
	if !plan.ProjectNames.IsNull() || state != nil && !state.ProjectNames.IsNull() {
		vProjectNames := make([]string, 0)
		diags := plan.ProjectNames.ElementsAs(ctx, &vProjectNames, false)
		if diags.HasError() {
			return diags
		}
		api.ProjectNames = &vProjectNames
	}
	if !plan.CustomCloudEnvironmentID.IsNull() || state != nil && !state.CustomCloudEnvironmentID.IsNull() {
		vCustomCloudEnvironmentID := plan.CustomCloudEnvironmentID.ValueString()
		api.CustomCloudEnvironmentID = &vCustomCloudEnvironmentID
	}
	if !plan.OrganizationID.IsNull() || state != nil && !state.OrganizationID.IsNull() {
		vOrganizationID := plan.OrganizationID.ValueString()
		api.OrganizationID = &vOrganizationID
	}
	err := util.Remarshal(api, req, plan, modifiers...)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("Remarshal error", fmt.Sprintf("Failed to remarshal dtoModel to Request: %s", err.Error()))
		return diags
	}
	return nil
}

// flattenData turns Response into TF object
func flattenData[R any](ctx context.Context, state *tfModel, rsp *R, modifiers ...util.MapModifier[tfModel]) diag.Diagnostics {
	api := new(apiModel)
	err := util.Remarshal(rsp, api, state, modifiers...)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("Remarshal error", fmt.Sprintf("Failed to remarshal Response to dtoModel: %s", err.Error()))
		return diags
	}
	if api.Accounts != nil && !state.Accounts.IsUnknown() {
		vAccounts, diags := util.SetValueFrom(ctx, types.StringType, api.Accounts)
		if diags.HasError() {
			return diags
		}
		state.Accounts = vAccounts
	}
	if api.ProjectNames != nil && !state.ProjectNames.IsUnknown() {
		vProjectNames, diags := util.SetValueFrom(ctx, types.StringType, api.ProjectNames)
		if diags.HasError() {
			return diags
		}
		state.ProjectNames = vProjectNames
	}
	if api.CustomCloudEnvironmentID != nil && !state.CustomCloudEnvironmentID.IsUnknown() {
		state.CustomCloudEnvironmentID = util.StringPointerValue(api.CustomCloudEnvironmentID)
	}
	if api.OrganizationID != nil && !state.OrganizationID.IsUnknown() {
		state.OrganizationID = util.StringPointerValue(api.OrganizationID)
	}
	// Response may not contain ID fields.
	// In that case, `terraform import` won't be able to set them. Gets values from the ID.
	if state.ID.ValueString() != "" {
		var parts [2]string
		for i, v := range strings.SplitN(state.ID.ValueString(), "/", 2) {
			parts[i] = v
		}
		if state.OrganizationID.ValueString() == "" {
			state.OrganizationID = types.StringValue(parts[0])
		}
		if state.CustomCloudEnvironmentID.ValueString() == "" {
			state.CustomCloudEnvironmentID = types.StringValue(parts[1])
		}
	}
	state.SetID(state.OrganizationID.ValueString(), state.CustomCloudEnvironmentID.ValueString())
	return nil
}
