package user_test

import (
	"context"
	"fmt"
	"strings"
	"testing"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	acc "github.com/aiven/terraform-provider-aiven/internal/acctest"
	"github.com/aiven/terraform-provider-aiven/internal/schemautil"
)

func TestAccAivenMySQLUser_basic(t *testing.T) {
	projectName := acc.ProjectName()
	serviceName := acc.RandName("mysql")
	serviceIsReady := acc.CreateTestService(
		t,
		projectName,
		serviceName,
		acc.WithServiceType("mysql"),
		acc.WithPlan("startup-4"),
		acc.WithCloud("google-europe-west1"),
	)

	client, err := acc.GetTestGenAivenClient()
	require.NoError(t, err)

	t.Run("basic test", func(t *testing.T) {
		resourceName := "aiven_mysql_user.foo"
		userName := acc.RandName("user")

		resource.ParallelTest(t, resource.TestCase{
			PreCheck:                 func() { acc.TestAccPreCheck(t) },
			ProtoV6ProviderFactories: acc.TestProtoV6ProviderFactories,
			CheckDestroy:             testAccCheckAivenMySQLUserResourceDestroy,
			Steps: []resource.TestStep{
				{
					// create with optional password
					PreConfig: func() {
						require.NoError(t, <-serviceIsReady)
					},
					Config: testAccMySQLUserResource(projectName, serviceName, userName, "Test$1234"),
					Check: resource.ComposeTestCheckFunc(
						// Basic attributes
						resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
						resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
						resource.TestCheckResourceAttr(resourceName, "username", userName),

						// Password - using optional password
						resource.TestCheckResourceAttr(resourceName, "password", "Test$1234"),
						resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
						resource.TestCheckNoResourceAttr(resourceName, "password_wo_version"),

						// Data source
						schemautil.TestAccCheckAivenServiceUserAttributes("data.aiven_mysql_user.user"),
					),
				},
				{
					// update optional password
					Config: testAccMySQLUserResource(projectName, serviceName, userName, "UpdatedP@ss5678"),
					Check: resource.ComposeTestCheckFunc(
						// Basic attributes
						resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
						resource.TestCheckResourceAttr(resourceName, "project", projectName),
						resource.TestCheckResourceAttr(resourceName, "username", userName),

						// Password - updated optional password
						resource.TestCheckResourceAttr(resourceName, "password", "UpdatedP@ss5678"),
						resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
						resource.TestCheckNoResourceAttr(resourceName, "password_wo_version"),

						// Data source
						schemautil.TestAccCheckAivenServiceUserAttributes("data.aiven_mysql_user.user"),
					),
				},
				{
					// transition to auto-generated password
					Config: testAccMySQLUserAutoGeneratedPassword(projectName, serviceName, userName),
					Check: resource.ComposeTestCheckFunc(
						// Basic attributes
						resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
						resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
						resource.TestCheckResourceAttr(resourceName, "username", userName),

						// Password - auto-generated
						resource.TestCheckResourceAttrSet(resourceName, "password"),
						resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
						resource.TestCheckNoResourceAttr(resourceName, "password_wo_version"),
					),
				},
				{
					// back to optional password
					Config: testAccMySQLUserResource(projectName, serviceName, userName, "Optional$Pass123"),
					Check: resource.ComposeTestCheckFunc(
						// Basic attributes
						resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
						resource.TestCheckResourceAttr(resourceName, "project", projectName),
						resource.TestCheckResourceAttr(resourceName, "username", userName),

						// Password - back to optional
						resource.TestCheckResourceAttr(resourceName, "password", "Optional$Pass123"),
						resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
						resource.TestCheckNoResourceAttr(resourceName, "password_wo_version"),
					),
				},
				{
					// transition to write-only password
					Config: testAccMySQLUserWriteOnlyPassword(projectName, serviceName, userName, 1),
					Check: resource.ComposeTestCheckFunc(
						// Basic attributes
						resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
						resource.TestCheckResourceAttr(resourceName, "project", projectName),
						resource.TestCheckResourceAttr(resourceName, "username", userName),

						// Password - using write-only password (password cleared, version set)
						resource.TestCheckNoResourceAttr(resourceName, "password"),
						resource.TestCheckResourceAttr(resourceName, "password_wo_version", "1"),

						// Checks if password_wo was actually set in Aiven
						func(state *terraform.State) error {
							rsp, err := client.ServiceUserGet(t.Context(), projectName, serviceName, userName)
							require.NoError(t, err)
							assert.Equal(t, "WriteOnlyPass$1", rsp.Password)
							return nil
						},
					),
				},
				{
					// rotate write-only password
					Config: testAccMySQLUserWriteOnlyPassword(projectName, serviceName, userName, 2),
					Check: resource.ComposeTestCheckFunc(
						// Basic attributes
						resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
						resource.TestCheckResourceAttr(resourceName, "project", projectName),
						resource.TestCheckResourceAttr(resourceName, "username", userName),

						// Password - rotated write-only password (password cleared, version incremented)
						resource.TestCheckNoResourceAttr(resourceName, "password"),
						resource.TestCheckResourceAttr(resourceName, "password_wo_version", "2"),

						// Checks if password_wo was actually updated in Aiven
						func(state *terraform.State) error {
							rsp, err := client.ServiceUserGet(t.Context(), projectName, serviceName, userName)
							require.NoError(t, err)
							assert.Equal(t, "WriteOnlyPass$2", rsp.Password)
							return nil
						},
					),
				},
				{
					// transition back to auto-generated password
					Config: testAccMySQLUserAutoGeneratedPassword(projectName, serviceName, userName),
					Check: resource.ComposeTestCheckFunc(
						// Basic attributes
						resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
						resource.TestCheckResourceAttr(resourceName, "project", projectName),
						resource.TestCheckResourceAttr(resourceName, "username", userName),

						// Password - back to auto-generated (password set, version removed)
						resource.TestCheckResourceAttrSet(resourceName, "password"),
						resource.TestCheckNoResourceAttr(resourceName, "password_wo"),

						// Checks if password_wo was actually removed in Aiven and autogenerated
						func(state *terraform.State) error {
							rsp, err := client.ServiceUserGet(t.Context(), projectName, serviceName, userName)
							require.NoError(t, err)
							assert.NotEqual(t, "WriteOnlyPass$2", rsp.Password)
							assert.True(t, strings.HasPrefix(rsp.Password, "AVN")) // Freshly generated
							return nil
						},
					),
				},
			},
		})
	})

	t.Run("compatibility test", func(t *testing.T) {
		userName := acc.RandName("user")
		config := fmt.Sprintf(`
resource "aiven_mysql_user" "test" {
  project      = %[1]q
  service_name = %[2]q
  username     = %[3]q
}

data "aiven_mysql_user" "test" {
  project      = aiven_mysql_user.test.project
  service_name = aiven_mysql_user.test.service_name
  username     = aiven_mysql_user.test.username
}`, projectName, serviceName, userName)

		resource.ParallelTest(t, resource.TestCase{
			PreCheck: func() { acc.TestAccPreCheck(t) },
			Steps: acc.BackwardCompatibilitySteps(t, acc.BackwardCompatConfig{
				TFConfig: config,
				PreConfig: func() {
					require.NoError(t, <-serviceIsReady)
				},
				OldProviderVersion: "4.47.0",
				Checks: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttrSet("aiven_mysql_user.test", "id"),
					resource.TestCheckResourceAttr("aiven_mysql_user.test", "username", userName),
					resource.TestCheckResourceAttrSet("aiven_mysql_user.test", "password"),
					resource.TestCheckResourceAttr("aiven_mysql_user.test", "type", "normal"),

					resource.TestCheckResourceAttr("data.aiven_mysql_user.test", "username", userName),
					resource.TestCheckResourceAttrSet("data.aiven_mysql_user.test", "password"),
				),
			}),
		})
	})
}

func testAccCheckAivenMySQLUserResourceDestroy(s *terraform.State) error {
	c, err := acc.GetTestGenAivenClient()
	if err != nil {
		return fmt.Errorf("error instantiating client: %w", err)
	}

	ctx := context.Background()

	// loop through the resources in state, verifying each aiven_mysql_user is destroyed
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "aiven_mysql_user" {
			continue
		}

		projectName, serviceName, username, err := schemautil.SplitResourceID3(rs.Primary.ID)
		if err != nil {
			return err
		}

		_, err = c.ServiceUserGet(ctx, projectName, serviceName, username)
		if err != nil && !avngen.IsNotFound(err) {
			return fmt.Errorf("error checking if user was destroyed: %w", err)
		}

		if err == nil {
			return fmt.Errorf("mysql user (%s) still exists", rs.Primary.ID)
		}
	}

	return nil
}

func testAccMySQLUserResource(projectName, serviceName, userName, password string) string {
	return fmt.Sprintf(`
resource "aiven_mysql_user" "foo" {
  project      = %[1]q
  service_name = %[2]q
  username     = %[3]q
  password     = "%s"
}

data "aiven_mysql_user" "user" {
  service_name = aiven_mysql_user.foo.service_name
  project      = aiven_mysql_user.foo.project
  username     = aiven_mysql_user.foo.username
}`, projectName, serviceName, userName, password)
}

func testAccMySQLUserAutoGeneratedPassword(projectName, serviceName, userName string) string {
	return fmt.Sprintf(`
resource "aiven_mysql_user" "foo" {
  project      = %[1]q
  service_name = %[2]q
  username     = %[3]q
}
`, projectName, serviceName, userName)
}

func testAccMySQLUserWriteOnlyPassword(projectName, serviceName, userName string, version int) string {
	return fmt.Sprintf(`
resource "aiven_mysql_user" "foo" {
  project             = %[1]q
  service_name        = %[2]q
  username            = %[3]q
  password_wo         = "WriteOnlyPass$%[4]d"
  password_wo_version = %[4]d
}
`, projectName, serviceName, userName, version)
}
