// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package address

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

/*
resourceSchema:

	resource "aiven_organization_address" "example" {
	  organization_id = "org1a23f456789" // Force new
	  address_lines   = ["Main Street 1"]
	  city            = "Helsinki"
	  country_code    = "FI"
	  name            = "Aiven Oy"
	  state           = "foo"
	  zip_code        = "01234"

	  // COMPUTED FIELDS
	  create_time = "foo"
	  update_time = "foo"
	  address_id  = "foo"
	}
*/
func resourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"address_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Address ID.",
			},
			"address_lines": schema.ListAttribute{
				ElementType:         types.StringType,
				MarkdownDescription: "Address Lines.",
				Required:            true,
				Validators:          []validator.List{listvalidator.SizeBetween(1, 5)},
			},
			"city": schema.StringAttribute{
				MarkdownDescription: "City. Maximum length: `125`.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(125)},
			},
			"country_code": schema.StringAttribute{
				MarkdownDescription: "Country Code. Maximum length: `2`.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(2)},
			},
			"create_time": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Create Time.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `organization_id/address_id`.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of a company. Length must be between `1` and `128`.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthBetween(1, 128)},
			},
			"organization_id": schema.StringAttribute{
				MarkdownDescription: "ID of an organization. Maximum length: `36`. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(36)},
			},
			"state": schema.StringAttribute{
				MarkdownDescription: "State. Maximum length: `128`.",
				Optional:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(128)},
			},
			"update_time": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Update Time.",
			},
			"zip_code": schema.StringAttribute{
				MarkdownDescription: "Zip Code. Maximum length: `10`.",
				Optional:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(10)},
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": timeouts.BlockAll(ctx)},
		MarkdownDescription: "Creates and manages an organization address. \n\n**This resource is in the beta stage and may change without notice.** Set\nthe `PROVIDER_AIVEN_ENABLE_BETA` environment variable to use the resource.",
	}
}
func resourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"address_id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"address_lines": &adapter.Schema{
				Items:          &adapter.Schema{Type: adapter.SchemaTypeString},
				Type:           adapter.SchemaTypeList,
				ZeroNotAllowed: true,
			},
			"city":         &adapter.Schema{Type: adapter.SchemaTypeString},
			"country_code": &adapter.Schema{Type: adapter.SchemaTypeString},
			"create_time": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"name": &adapter.Schema{
				Type:           adapter.SchemaTypeString,
				ZeroNotAllowed: true,
			},
			"organization_id": &adapter.Schema{Type: adapter.SchemaTypeString},
			"state":           &adapter.Schema{Type: adapter.SchemaTypeString},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{
					"create": &adapter.Schema{Type: adapter.SchemaTypeString},
					"delete": &adapter.Schema{Type: adapter.SchemaTypeString},
					"read":   &adapter.Schema{Type: adapter.SchemaTypeString},
					"update": &adapter.Schema{Type: adapter.SchemaTypeString},
				},
				Type: adapter.SchemaTypeObject,
			},
			"update_time": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"zip_code": &adapter.Schema{Type: adapter.SchemaTypeString},
		},
		Type: adapter.SchemaTypeObject,
	}
}
