version: "2"

linters:
  run:
    timeout: 5m
  default: none
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - testifylint
  settings:
    lll:
      line-length: 140
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: internal/sdkprovider/service/account/account_team.*
      - linters:
          - staticcheck
        path: internal/sdkprovider/service/account/sweep.go
        text: 'SA1019: (.*) is deprecated'
      - linters:
         - staticcheck
        text: 'QF1012: (.*)'
      - path: (.+)\.go$
        text: 'var-naming: .*'
      - path: (.+)\.go$
        text: 'exported: .*'
      - linters:
          - testifylint
        path: examples_tests/.*_test\.go$
        text: 'require-error: for error assertions use require'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
