dir: mocks
pkgname: mocks
template: testify
filename: "{{ .InterfaceName | lower }}.go"
formatter: goimports
packages:
  github.com/aiven/terraform-provider-aiven/internal/schemautil:
    interfaces:
      ResourceData: {}
