// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package jarapplication

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/legacytimeouts"
)

func resourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"application_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Application ID.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"application_versions": schema.ListNestedAttribute{
				Computed:            true,
				MarkdownDescription: "JarApplicationVersions.",
				NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "The creation timestamp of this entity in ISO 8601 format, always in UTC.",
					},
					"created_by": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "The creator of this entity.",
					},
					"file_info": schema.ListNestedAttribute{
						Computed:            true,
						MarkdownDescription: "Flink JarApplicationVersion FileInfo.",
						NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
							"file_sha256": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "sha256 of the file if known.",
							},
							"file_size": schema.Int64Attribute{
								Computed:            true,
								MarkdownDescription: "The size of the file in bytes.",
							},
							"file_status": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "Indicates whether the uploaded .jar file has been verified by the system and deployment ready. The possible values are `FAILED`, `INITIAL` and `READY`.",
							},
							"url": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "The pre-signed url of the bucket where the .jar file is uploaded. Becomes null when the JarApplicationVersion is ready or failed.",
							},
							"verify_error_code": schema.Int64Attribute{
								Computed:            true,
								MarkdownDescription: "In the case file_status is FAILED, the error code of the failure. The possible values are `1`, `2`, `3` and `4`.",
							},
							"verify_error_message": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "In the case file_status is FAILED, may contain details about the failure.",
							},
						}},
					},
					"id": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "ApplicationVersion ID.",
					},
					"version": schema.Int64Attribute{
						Computed:            true,
						MarkdownDescription: "Version number.",
					},
				}},
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The creation timestamp of this entity in ISO 8601 format, always in UTC.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"created_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The creator of this entity.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"current_deployment": schema.ListNestedAttribute{
				Computed:            true,
				MarkdownDescription: "Flink JarApplicationDeployment.",
				NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "The creation timestamp of this entity in ISO 8601 format, always in UTC.",
					},
					"created_by": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "The creator of this entity.",
					},
					"entry_class": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "The fully qualified name of the entry class to pass during Flink job submission through the entryClass parameter.",
					},
					"error_msg": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Error message describing what caused deployment to fail.",
					},
					"id": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Deployment ID.",
					},
					"job_id": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Job ID.",
					},
					"last_savepoint": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Job savepoint.",
					},
					"parallelism": schema.Int64Attribute{
						Computed:            true,
						MarkdownDescription: "Reading of Flink parallel execution documentation is recommended before setting this value to other than 1. Please do not set this value higher than (total number of nodes x number_of_task_slots), or every new job created will fail.",
					},
					"program_args": schema.SetAttribute{
						Computed:            true,
						ElementType:         types.StringType,
						MarkdownDescription: "Arguments to pass during Flink job submission through the programArgsList parameter.",
					},
					"starting_savepoint": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Job savepoint.",
					},
					"status": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Deployment status. The possible values are `CANCELED`, `CANCELLING`, `CANCELLING_REQUESTED`, `CREATED`, `DELETE_REQUESTED`, `DELETING`, `FAILED`, `FAILING`, `FINISHED`, `INITIALIZING`, `RECONCILING`, `RESTARTING`, `RUNNING`, `SAVING`, `SAVING_AND_STOP`, `SAVING_AND_STOP_REQUESTED` and `SUSPENDED`.",
					},
					"version_id": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "ApplicationVersion ID.",
					},
				}},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `project/service_name/application_id`.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Application name. Maximum length: `128`.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(128)},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"service_name": schema.StringAttribute{
				MarkdownDescription: "Service name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The update timestamp of this entity in ISO 8601 format, always in UTC.",
			},
			"updated_by": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The latest updater of this entity.",
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": legacytimeouts.BlockAll(ctx)},
		MarkdownDescription: "Creates and manages an [Aiven for Apache Flink® jar application](https://aiven.io/docs/products/flink/howto/create-jar-application). Requires the `aiven_flink` service to have `flink_user_config.custom_code` enabled, which allows uploading and deploying custom JARs. \n\n**This resource is in the beta stage and may change without notice.** Set\nthe `PROVIDER_AIVEN_ENABLE_BETA` environment variable to use the resource. If this resource is missing (for example, after a service power off), it's removed from the state and a new create plan is generated.",
	}
}
func resourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"application_id": &adapter.Schema{
				Computed:       true,
				Type:           adapter.SchemaTypeString,
				ZeroNotAllowed: true,
			},
			"application_versions": &adapter.Schema{
				Computed:    true,
				IsAttribute: true,
				Items: &adapter.Schema{
					Computed:    true,
					IsAttribute: true,
					Properties: map[string]*adapter.Schema{
						"created_at": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"created_by": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"file_info": &adapter.Schema{
							Computed:    true,
							IsAttribute: true,
							IsObject:    true,
							Items: &adapter.Schema{
								Computed:    true,
								IsAttribute: true,
								Properties: map[string]*adapter.Schema{
									"file_sha256": &adapter.Schema{
										Computed:       true,
										Type:           adapter.SchemaTypeString,
										ZeroNotAllowed: true,
									},
									"file_size": &adapter.Schema{
										Computed: true,
										Type:     adapter.SchemaTypeInt,
									},
									"file_status": &adapter.Schema{
										Computed: true,
										Type:     adapter.SchemaTypeString,
									},
									"url": &adapter.Schema{
										Computed:       true,
										Type:           adapter.SchemaTypeString,
										ZeroNotAllowed: true,
									},
									"verify_error_code": &adapter.Schema{
										Computed: true,
										Type:     adapter.SchemaTypeInt,
									},
									"verify_error_message": &adapter.Schema{
										Computed:       true,
										Type:           adapter.SchemaTypeString,
										ZeroNotAllowed: true,
									},
								},
								Type: adapter.SchemaTypeObject,
							},
							Type: adapter.SchemaTypeList,
						},
						"id": &adapter.Schema{
							Computed:       true,
							Type:           adapter.SchemaTypeString,
							ZeroNotAllowed: true,
						},
						"version": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeInt,
						},
					},
					Type: adapter.SchemaTypeObject,
				},
				Type: adapter.SchemaTypeList,
			},
			"created_at": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"created_by": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"current_deployment": &adapter.Schema{
				Computed:    true,
				IsAttribute: true,
				IsObject:    true,
				Items: &adapter.Schema{
					Computed:    true,
					IsAttribute: true,
					Properties: map[string]*adapter.Schema{
						"created_at": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"created_by": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"entry_class": &adapter.Schema{
							Computed:       true,
							Type:           adapter.SchemaTypeString,
							ZeroNotAllowed: true,
						},
						"error_msg": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"id": &adapter.Schema{
							Computed:       true,
							Type:           adapter.SchemaTypeString,
							ZeroNotAllowed: true,
						},
						"job_id": &adapter.Schema{
							Computed:       true,
							Type:           adapter.SchemaTypeString,
							ZeroNotAllowed: true,
						},
						"last_savepoint": &adapter.Schema{
							Computed:       true,
							Type:           adapter.SchemaTypeString,
							ZeroNotAllowed: true,
						},
						"parallelism": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeInt,
						},
						"program_args": &adapter.Schema{
							Computed: true,
							Items: &adapter.Schema{
								Computed: true,
								Type:     adapter.SchemaTypeString,
							},
							Type: adapter.SchemaTypeSet,
						},
						"starting_savepoint": &adapter.Schema{
							Computed:       true,
							Type:           adapter.SchemaTypeString,
							ZeroNotAllowed: true,
						},
						"status": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"version_id": &adapter.Schema{
							Computed:       true,
							Type:           adapter.SchemaTypeString,
							ZeroNotAllowed: true,
						},
					},
					Type: adapter.SchemaTypeObject,
				},
				Type: adapter.SchemaTypeList,
			},
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"name":         &adapter.Schema{Type: adapter.SchemaTypeString},
			"project":      &adapter.Schema{Type: adapter.SchemaTypeString},
			"service_name": &adapter.Schema{Type: adapter.SchemaTypeString},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{
					"create":  &adapter.Schema{Type: adapter.SchemaTypeString},
					"default": &adapter.Schema{Type: adapter.SchemaTypeString},
					"delete":  &adapter.Schema{Type: adapter.SchemaTypeString},
					"read":    &adapter.Schema{Type: adapter.SchemaTypeString},
					"update":  &adapter.Schema{Type: adapter.SchemaTypeString},
				},
				Type: adapter.SchemaTypeObject,
			},
			"updated_at": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"updated_by": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
		},
		Type: adapter.SchemaTypeObject,
	}
}
