// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package application

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/util"
)

const typeName = "aiven_flink_application"

type tfModel struct {
	ID            types.String `tfsdk:"id"`
	ApplicationID types.String `tfsdk:"application_id"`
	CreatedAt     types.String `tfsdk:"created_at"`
	CreatedBy     types.String `tfsdk:"created_by"`
	Name          types.String `tfsdk:"name"`
	Project       types.String `tfsdk:"project"`
	ServiceName   types.String `tfsdk:"service_name"`
	UpdatedAt     types.String `tfsdk:"updated_at"`
	UpdatedBy     types.String `tfsdk:"updated_by"`
}

func (tf *tfModel) SetID(vProject string, vServiceName string, vApplicationID string) {
	tf.Project = types.StringValue(vProject)
	tf.ServiceName = types.StringValue(vServiceName)
	tf.ApplicationID = types.StringValue(vApplicationID)
	tf.ID = types.StringValue(filepath.Join(vProject, vServiceName, vApplicationID))
}

type apiModel struct {
	ApplicationID *string `json:"id,omitempty"`
	CreatedAt     *string `json:"created_at,omitempty"`
	CreatedBy     *string `json:"created_by,omitempty"`
	Name          *string `json:"name,omitempty"`
	Project       *string `json:"project,omitempty"`
	ServiceName   *string `json:"service_name,omitempty"`
	UpdatedAt     *string `json:"updated_at,omitempty"`
	UpdatedBy     *string `json:"updated_by,omitempty"`
}

// idFields the ID attribute fields, i.e.:
// terraform import aiven_flink_application.foo PROJECT/SERVICE_NAME/APPLICATION_ID
func idFields() []string {
	return []string{"project", "service_name", "application_id"}
}

// expandData turns TF object into Request
func expandData[R any](ctx context.Context, plan, state *tfModel, req *R, modifiers ...util.MapModifier[tfModel]) diag.Diagnostics {
	api := new(apiModel)
	if !plan.Name.IsNull() || state != nil && !state.Name.IsNull() {
		vName := plan.Name.ValueString()
		api.Name = &vName
	}
	if !plan.Project.IsNull() || state != nil && !state.Project.IsNull() {
		vProject := plan.Project.ValueString()
		api.Project = &vProject
	}
	if !plan.ServiceName.IsNull() || state != nil && !state.ServiceName.IsNull() {
		vServiceName := plan.ServiceName.ValueString()
		api.ServiceName = &vServiceName
	}
	err := util.Remarshal(api, req, plan, modifiers...)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("Remarshal error", fmt.Sprintf("Failed to remarshal dtoModel to Request: %s", err.Error()))
		return diags
	}
	return nil
}

// flattenData turns Response into TF object
func flattenData[R any](ctx context.Context, state *tfModel, rsp *R, modifiers ...util.MapModifier[tfModel]) diag.Diagnostics {
	api := new(apiModel)
	err := util.Remarshal(rsp, api, state, modifiers...)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("Remarshal error", fmt.Sprintf("Failed to remarshal Response to dtoModel: %s", err.Error()))
		return diags
	}
	if api.ApplicationID != nil || state.ApplicationID.IsUnknown() {
		state.ApplicationID = util.StringPointerValue(api.ApplicationID)
	}
	if api.CreatedAt != nil || state.CreatedAt.IsUnknown() {
		state.CreatedAt = util.StringPointerValue(api.CreatedAt)
	}
	if api.CreatedBy != nil || state.CreatedBy.IsUnknown() {
		state.CreatedBy = util.StringPointerValue(api.CreatedBy)
	}
	if api.Name != nil && !state.Name.IsUnknown() {
		state.Name = util.StringPointerValue(api.Name)
	}
	if api.Project != nil && !state.Project.IsUnknown() {
		state.Project = util.StringPointerValue(api.Project)
	}
	if api.ServiceName != nil && !state.ServiceName.IsUnknown() {
		state.ServiceName = util.StringPointerValue(api.ServiceName)
	}
	if api.UpdatedAt != nil || state.UpdatedAt.IsUnknown() {
		state.UpdatedAt = util.StringPointerValue(api.UpdatedAt)
	}
	if api.UpdatedBy != nil || state.UpdatedBy.IsUnknown() {
		state.UpdatedBy = util.StringPointerValue(api.UpdatedBy)
	}
	// Response may not contain ID fields.
	// In that case, `terraform import` won't be able to set them. Gets values from the ID.
	if state.ID.ValueString() != "" {
		var parts [3]string
		for i, v := range strings.SplitN(state.ID.ValueString(), "/", 3) {
			parts[i] = v
		}
		if state.Project.ValueString() == "" {
			state.Project = types.StringValue(parts[0])
		}
		if state.ServiceName.ValueString() == "" {
			state.ServiceName = types.StringValue(parts[1])
		}
		if state.ApplicationID.ValueString() == "" {
			state.ApplicationID = types.StringValue(parts[2])
		}
	}
	state.SetID(state.Project.ValueString(), state.ServiceName.ValueString(), state.ApplicationID.ValueString())
	return nil
}
