// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package application

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/aiven/go-client-codegen/handler/flinkapplication"
	"github.com/hashicorp/terraform-plugin-framework-validators/datasourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/path"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

const typeName = "aiven_flink_application"

// idFields the ID attribute fields, i.e.:
// terraform import aiven_flink_application.foo PROJECT/SERVICE_NAME/APPLICATION_ID
func idFields() []string {
	return []string{"project", "service_name", "application_id"}
}

var ResourceOptions = adapter.ResourceOptions{
	Create:         createView,
	Delete:         deleteView,
	IDFields:       idFields(),
	Read:           readView,
	RefreshState:   true,
	RemoveMissing:  true,
	Schema:         resourceSchema,
	SchemaInternal: resourceSchemaInternal(),
	TypeName:       typeName,
	Update:         updateView,
}

var DataSourceOptions = adapter.DataSourceOptions{
	ConfigValidators: datasourceConfigValidators,
	IDFields:         idFields(),
	Read:             readView,
	Schema:           datasourceSchema,
	SchemaInternal:   datasourceSchemaInternal(),
	TypeName:         typeName,
}

func createView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	req := new(flinkapplication.ServiceFlinkCreateApplicationIn)
	err := d.Expand(req)
	if err != nil {
		return err
	}
	rsp, err := client.ServiceFlinkCreateApplication(ctx, d.Get("project").(string), d.Get("service_name").(string), req)
	if err != nil {
		return err
	}
	return d.Flatten(rsp, adapter.RenameFields(map[string]string{"id": "application_id"}))
}

func readView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	err := planModifier(ctx, client, d)
	if err != nil {
		return err
	}
	rsp, err := client.ServiceFlinkGetApplication(ctx, d.Get("project").(string), d.Get("service_name").(string), d.Get("application_id").(string))
	if err != nil {
		return err
	}
	return d.Flatten(rsp, adapter.RenameFields(map[string]string{"id": "application_id"}))
}

func updateView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	req := new(flinkapplication.ServiceFlinkUpdateApplicationIn)
	err := d.Expand(req)
	if err != nil {
		return err
	}
	rsp, err := client.ServiceFlinkUpdateApplication(ctx, d.Get("project").(string), d.Get("service_name").(string), d.Get("application_id").(string), req)
	if err != nil {
		return err
	}
	return d.Flatten(rsp, adapter.RenameFields(map[string]string{"id": "application_id"}))
}

func deleteView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	_, err := client.ServiceFlinkDeleteApplication(ctx, d.Get("project").(string), d.Get("service_name").(string), d.Get("application_id").(string))
	return err
}

func datasourceConfigValidators(ctx context.Context, client avngen.Client) []datasource.ConfigValidator {
	return []datasource.ConfigValidator{
		datasourcevalidator.ExactlyOneOf(
			path.MatchRoot("application_id"),
			path.MatchRoot("name"),
		),
	}
}
