// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package application

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/aiven/go-client-codegen/handler/flinkapplication"
	"github.com/hashicorp/terraform-plugin-framework/diag"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/errmsg"
)

var ResourceOptions = adapter.ResourceOptions[*resourceModel, tfModel]{
	Create:        createView,
	Delete:        deleteView,
	IDFields:      idFields(),
	Read:          readView,
	RefreshState:  true,
	RemoveMissing: true,
	Schema:        resourceSchema,
	TypeName:      typeName,
	Update:        updateView,
}

var DataSourceOptions = adapter.DataSourceOptions[*datasourceModel, tfModel]{
	Read:     readView,
	Schema:   datasourceSchema,
	TypeName: typeName,
}

func createView(ctx context.Context, client avngen.Client, plan, config *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		var req flinkapplication.ServiceFlinkCreateApplicationIn
		diags.Append(expandData(ctx, plan, nil, &req)...)
		if diags.HasError() {
			return
		}

		rsp, err := client.ServiceFlinkCreateApplication(ctx, plan.Project.ValueString(), plan.ServiceName.ValueString(), &req)
		if err != nil {
			diags.Append(errmsg.FromError("ServiceFlinkCreateApplication Error", err))
			return
		}
		diags.Append(flattenData(ctx, plan, rsp)...)
	}()
	return diags
}

func readView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		rsp, err := client.ServiceFlinkGetApplication(ctx, state.Project.ValueString(), state.ServiceName.ValueString(), state.ApplicationID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("ServiceFlinkGetApplication Error", err))
			return
		}
		diags.Append(flattenData(ctx, state, rsp)...)
	}()
	return diags
}

func updateView(ctx context.Context, client avngen.Client, plan, state, config *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		var req flinkapplication.ServiceFlinkUpdateApplicationIn
		diags.Append(expandData(ctx, plan, state, &req)...)
		if diags.HasError() {
			return
		}

		rsp, err := client.ServiceFlinkUpdateApplication(ctx, state.Project.ValueString(), state.ServiceName.ValueString(), state.ApplicationID.ValueString(), &req)
		if err != nil {
			diags.Append(errmsg.FromError("ServiceFlinkUpdateApplication Error", err))
			return
		}
		diags.Append(flattenData(ctx, plan, rsp)...)
	}()
	return diags
}

func deleteView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		_, err := client.ServiceFlinkDeleteApplication(ctx, state.Project.ValueString(), state.ServiceName.ValueString(), state.ApplicationID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("ServiceFlinkDeleteApplication Error", err))
			return
		}
	}()
	return diags
}
