// Code generated by user config generator. DO NOT EDIT.

package serviceintegration

import "github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

func GetUserConfig(kind string) *schema.Schema {
	switch kind {
	case "clickhouse_credentials":
		return clickhouseCredentialsUserConfig()
	case "clickhouse_kafka":
		return clickhouseKafkaUserConfig()
	case "clickhouse_postgresql":
		return clickhousePostgresqlUserConfig()
	case "datadog":
		return datadogUserConfig()
	case "external_aws_cloudwatch_logs":
		return externalAwsCloudwatchLogsUserConfig()
	case "external_aws_cloudwatch_metrics":
		return externalAwsCloudwatchMetricsUserConfig()
	case "external_elasticsearch_logs":
		return externalElasticsearchLogsUserConfig()
	case "external_opensearch_logs":
		return externalOpensearchLogsUserConfig()
	case "flink_external_postgresql":
		return flinkExternalPostgresqlUserConfig()
	case "kafka_connect":
		return kafkaConnectUserConfig()
	case "kafka_logs":
		return kafkaLogsUserConfig()
	case "kafka_mirrormaker":
		return kafkaMirrormakerUserConfig()
	case "logs":
		return logsUserConfig()
	case "metrics":
		return metricsUserConfig()
	case "prometheus":
		return prometheusUserConfig()
	default:
		return nil
	}
}

// GetFieldMapping returns TF fields to Json fields mapping (in unix-path way)
func GetFieldMapping(kind string) map[string]string {
	return map[string]map[string]string{}[kind]
}
func UserConfigTypes() []string {
	return []string{"clickhouse_credentials", "clickhouse_kafka", "clickhouse_postgresql", "datadog", "external_aws_cloudwatch_logs", "external_aws_cloudwatch_metrics", "external_elasticsearch_logs", "external_opensearch_logs", "flink_external_postgresql", "kafka_connect", "kafka_logs", "kafka_mirrormaker", "logs", "metrics", "prometheus"}
}
