package kafka_test

import (
	"context"
	"fmt"
	"regexp"
	"testing"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/hashicorp/terraform-plugin-testing/helper/acctest"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	acc "github.com/aiven/terraform-provider-aiven/internal/acctest"
	"github.com/aiven/terraform-provider-aiven/internal/schemautil"
)

func TestAccAivenKafkaUser(t *testing.T) {
	resourceName := "aiven_kafka_user.foo"
	rName := acctest.RandStringFromCharSet(10, acctest.CharSetAlphaNum)

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acc.TestAccPreCheck(t) },
		ProtoV6ProviderFactories: acc.TestProtoV6ProviderFactories,
		ExternalProviders: map[string]resource.ExternalProvider{
			"random": {
				Source:            "hashicorp/random",
				VersionConstraint: ">= 3.0.0",
			},
		},
		CheckDestroy: testAccCheckAivenKafkaUserResourceDestroy,
		Steps: []resource.TestStep{
			{
				// password validation: password too short
				Config:      testAccKafkaUserResource(rName, "short"),
				ExpectError: regexp.MustCompile(`expected length of password to be in the range \(8 - 256\)`),
			},
			{
				// password validation: password_wo too short
				Config: fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "test-acc-sr-%s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name        = aiven_kafka.bar.service_name
  project             = data.aiven_project.foo.project
  username            = "user-%s"
  password_wo         = "short"
  password_wo_version = 1
}
`, acc.ProjectName(), rName, rName),
				ExpectError: regexp.MustCompile(`expected length of password_wo to be in the range \(8 - 256\)`),
			},
			{
				// create with optional password
				Config: testAccKafkaUserResource(rName, "Test$1234"),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", fmt.Sprintf("test-acc-sr-%s", rName)),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", rName)),

					// Password - using optional password
					resource.TestCheckResourceAttr(resourceName, "password", "Test$1234"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo_version"),

					// Data source
					schemautil.TestAccCheckAivenServiceUserAttributes("data.aiven_kafka_user.user"),
				),
			},
			{
				// update optional password
				Config: testAccKafkaUserResource(rName, "UpdatedP@ss5678"),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", fmt.Sprintf("test-acc-sr-%s", rName)),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", rName)),

					// Password - updated optional password
					resource.TestCheckResourceAttr(resourceName, "password", "UpdatedP@ss5678"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo_version"),

					// Data source
					schemautil.TestAccCheckAivenServiceUserAttributes("data.aiven_kafka_user.user"),
				),
			},
			{
				// transition to auto-generated password
				Config: testAccKafkaUserAutoGeneratedPassword(rName),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", fmt.Sprintf("test-acc-sr-%s", rName)),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", rName)),

					// Password - auto-generated
					resource.TestCheckResourceAttrSet(resourceName, "password"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo_version"),
				),
			},
			{
				// back to optional password
				Config: testAccKafkaUserResource(rName, "Optional$Pass123"),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", fmt.Sprintf("test-acc-sr-%s", rName)),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", rName)),

					// Password - back to optional
					resource.TestCheckResourceAttr(resourceName, "password", "Optional$Pass123"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo_version"),
				),
			},
			{
				// transition to write-only password
				Config: testAccKafkaUserWriteOnlyPassword(rName, 1),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", fmt.Sprintf("test-acc-sr-%s", rName)),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", rName)),

					// Password - using write-only password (password cleared, version set)
					resource.TestCheckResourceAttr(resourceName, "password", ""),
					resource.TestCheckResourceAttr(resourceName, "password_wo_version", "1"),
				),
			},
			{
				// rotate write-only password
				Config: testAccKafkaUserWriteOnlyPassword(rName, 2),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", fmt.Sprintf("test-acc-sr-%s", rName)),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", rName)),

					// Password - rotated write-only password (password cleared, version incremented)
					resource.TestCheckResourceAttr(resourceName, "password", ""),
					resource.TestCheckResourceAttr(resourceName, "password_wo_version", "2"),
				),
			},
			{
				// transition back to auto-generated password
				Config: testAccKafkaUserAutoGeneratedPassword(rName),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", fmt.Sprintf("test-acc-sr-%s", rName)),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", rName)),

					// Password - back to auto-generated (password set, version reset to 0)
					resource.TestCheckResourceAttrSet(resourceName, "password"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
					resource.TestCheckResourceAttr(resourceName, "password_wo_version", "0"),
				),
			},
			{
				// optional password
				Config: testAccKafkaUserResource(rName, "FinalPass$456"),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", fmt.Sprintf("test-acc-sr-%s", rName)),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", rName)),

					// Password - final optional password
					resource.TestCheckResourceAttr(resourceName, "password", "FinalPass$456"),
					resource.TestCheckNoResourceAttr(resourceName, "password_wo"),
					resource.TestCheckResourceAttr(resourceName, "password_wo_version", "0"),
				),
			},
		},
	})
}

func TestAccAivenKafkaUser_passwordValidation(t *testing.T) {
	rName := acctest.RandStringFromCharSet(10, acctest.CharSetAlphaNum)

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acc.TestAccPreCheck(t) },
		ProtoV6ProviderFactories: acc.TestProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckAivenKafkaUserResourceDestroy,
		Steps: []resource.TestStep{
			{
				// password too short (less than 8 characters)
				Config:      testAccKafkaUserResource(rName, "short"),
				ExpectError: regexp.MustCompile(`expected length of password to be in the range \(8 - 256\)`),
			},
			{
				// password_wo too short (less than 8 characters)
				Config:      testAccKafkaUserWriteOnlyPasswordShort(rName),
				ExpectError: regexp.MustCompile(`expected length of password_wo to be in the range \(8 - 256\)`),
			},
			{
				// valid password with exactly 8 characters
				Config: testAccKafkaUserResource(rName, "Valid$12"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("aiven_kafka_user.foo", "password", "Valid$12"),
				),
			},
		},
	})
}

func testAccCheckAivenKafkaUserResourceDestroy(s *terraform.State) error {
	c, err := acc.GetTestGenAivenClient()
	if err != nil {
		return fmt.Errorf("error instantiating client: %w", err)
	}

	ctx := context.Background()

	// loop through the resources in state, verifying each aiven_kafka_user is destroyed
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "aiven_kafka_user" {
			continue
		}

		projectName, serviceName, username, err := schemautil.SplitResourceID3(rs.Primary.ID)
		if err != nil {
			return err
		}

		_, err = c.ServiceUserGet(ctx, projectName, serviceName, username)
		if err == nil {
			return fmt.Errorf("kafka user (%s) still exists", rs.Primary.ID)
		}

		if !avngen.IsNotFound(err) {
			return fmt.Errorf("error checking if user was destroyed: %w", err)
		}

		return nil
	}

	return nil
}

func testAccKafkaUserResource(name, password string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "test-acc-sr-%s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name = aiven_kafka.bar.service_name
  project      = data.aiven_project.foo.project
  username     = "user-%s"
  password     = "%s"
}

data "aiven_kafka_user" "user" {
  service_name = aiven_kafka_user.foo.service_name
  project      = aiven_kafka_user.foo.project
  username     = aiven_kafka_user.foo.username
}`, acc.ProjectName(), name, name, password)
}

func testAccKafkaUserAutoGeneratedPassword(name string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "test-acc-sr-%s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name = aiven_kafka.bar.service_name
  project      = data.aiven_project.foo.project
  username     = "user-%s"
}
`, acc.ProjectName(), name, name)
}

func testAccKafkaUserWriteOnlyPassword(name string, version int) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "test-acc-sr-%[2]s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name        = aiven_kafka.bar.service_name
  project             = data.aiven_project.foo.project
  username            = "user-%[2]s"
  password_wo         = "WriteOnlyPass$%[3]d"
  password_wo_version = %[3]d
}
`, acc.ProjectName(), name, version)
}

func testAccKafkaUserWriteOnlyPasswordShort(name string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "test-acc-sr-%[2]s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name        = aiven_kafka.bar.service_name
  project             = data.aiven_project.foo.project
  username            = "user-%[2]s"
  password_wo         = "short"
  password_wo_version = 1
}
`, acc.ProjectName(), name)
}
