package kafka_test

import (
	"context"
	"fmt"
	"regexp"
	"testing"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	acc "github.com/aiven/terraform-provider-aiven/internal/acctest"
	"github.com/aiven/terraform-provider-aiven/internal/schemautil"
)

func TestAccAivenKafkaUser(t *testing.T) {
	resourceName := "aiven_kafka_user.foo"
	serviceName := acc.RandName("kafka")
	userName := acc.RandStr()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acc.TestAccPreCheck(t) },
		ProtoV6ProviderFactories: acc.TestProtoV6ProviderFactories,
		ExternalProviders: map[string]resource.ExternalProvider{
			"random": {
				Source:            "hashicorp/random",
				VersionConstraint: ">= 3.0.0",
			},
		},
		CheckDestroy: testAccCheckAivenKafkaUserResourceDestroy,
		Steps: []resource.TestStep{
			{
				// password validation: password too short
				Config:      testAccKafkaUserResource(serviceName, userName, "short"),
				ExpectError: regexp.MustCompile(`expected length of password to be in the range \(8 - 256\)`),
			},
			{
				// password validation: password_wo too short
				Config: fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "%s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name        = aiven_kafka.bar.service_name
  project             = data.aiven_project.foo.project
  username            = "user-%s"
  password_wo         = "short"
  password_wo_version = 1
}
`, acc.ProjectName(), serviceName, userName),
				ExpectError: regexp.MustCompile(`expected length of password_wo to be in the range \(8 - 256\)`),
			},
			{
				// create with custom password
				Config: testAccKafkaUserResource(serviceName, userName, "acc-custom-Test$1234"),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),

					// Password validation
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-Test$1234"),

					// Data source
					schemautil.TestAccCheckAivenServiceUserAttributes("data.aiven_kafka_user.user"),
				),
			},
			{
				// update custom password
				Config: testAccKafkaUserResource(serviceName, userName, "acc-custom-UpdatedP@ss5678"),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),

					// Password validation
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-UpdatedP@ss5678"),

					// Data source
					schemautil.TestAccCheckAivenServiceUserAttributes("data.aiven_kafka_user.user"),
				),
			},
			{
				// transition to auto-generated password
				Config: testAccKafkaUserAutoGeneratedPassword(serviceName, userName),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),

					// Password validation
					acc.TestAccPasswordHasGeneratedPassword(resourceName),
				),
			},
			{
				// back to custom password
				Config: testAccKafkaUserResource(serviceName, userName, "acc-custom-Optional$Pass123"),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),

					// Password validation
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-Optional$Pass123"),
				),
			},
			{
				// transition to write-only password
				Config: testAccKafkaUserWriteOnlyPassword(serviceName, userName, 1),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),

					// Password validation
					acc.TestAccPasswordHasWOPassword(resourceName),
				),
			},
			{
				// rotate write-only password
				Config: testAccKafkaUserWriteOnlyPassword(serviceName, userName, 2),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),

					// Password validation
					acc.TestAccPasswordHasWOPassword(resourceName),
				),
			},
			{
				// transition back to auto-generated password
				Config: testAccKafkaUserAutoGeneratedPassword(serviceName, userName),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),

					// Password validation
					acc.TestAccPasswordHasGeneratedPassword(resourceName),
				),
			},
			{
				// custom password
				Config: testAccKafkaUserResource(serviceName, userName, "acc-custom-FinalPass$456"),
				Check: resource.ComposeTestCheckFunc(
					// Basic attributes
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),

					// Password validation
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-FinalPass$456"),
				),
			},
		},
	})
}

func TestAccAivenKafkaUser_passwordValidation(t *testing.T) {
	serviceName := acc.RandName("kafka-user-test")
	userName := acc.RandStr()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acc.TestAccPreCheck(t) },
		ProtoV6ProviderFactories: acc.TestProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckAivenKafkaUserResourceDestroy,
		Steps: []resource.TestStep{
			{
				// password too short (less than 8 characters)
				Config:      testAccKafkaUserResource(serviceName, userName, "short"),
				ExpectError: regexp.MustCompile(`expected length of password to be in the range \(8 - 256\)`),
			},
			{
				// password_wo too short (less than 8 characters)
				Config:      testAccKafkaUserWriteOnlyPasswordShort(serviceName, userName),
				ExpectError: regexp.MustCompile(`expected length of password_wo to be in the range \(8 - 256\)`),
			},
			{
				// valid password with exactly 8 characters
				Config: testAccKafkaUserResource(serviceName, userName, "Valid$12"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr("aiven_kafka_user.foo", "password", "Valid$12"),
				),
			},
		},
	})
}

func testAccCheckAivenKafkaUserResourceDestroy(s *terraform.State) error {
	c, err := acc.GetTestGenAivenClient()
	if err != nil {
		return fmt.Errorf("error instantiating client: %w", err)
	}

	ctx := context.Background()

	// loop through the resources in state, verifying each aiven_kafka_user is destroyed
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "aiven_kafka_user" {
			continue
		}

		projectName, serviceName, username, err := schemautil.SplitResourceID3(rs.Primary.ID)
		if err != nil {
			return err
		}

		_, err = c.ServiceUserGet(ctx, projectName, serviceName, username)
		if err == nil {
			return fmt.Errorf("kafka user (%s) still exists", rs.Primary.ID)
		}

		if !avngen.IsNotFound(err) {
			return fmt.Errorf("error checking if user was destroyed: %w", err)
		}

		return nil
	}

	return nil
}

func testAccKafkaUserResource(serviceName, userName, password string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "%s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name = aiven_kafka.bar.service_name
  project      = data.aiven_project.foo.project
  username     = "user-%s"
  password     = "%s"
}

data "aiven_kafka_user" "user" {
  service_name = aiven_kafka_user.foo.service_name
  project      = aiven_kafka_user.foo.project
  username     = aiven_kafka_user.foo.username
}`, acc.ProjectName(), serviceName, userName, password)
}

func testAccKafkaUserAutoGeneratedPassword(serviceName, userName string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "%s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name = aiven_kafka.bar.service_name
  project      = data.aiven_project.foo.project
  username     = "user-%s"
}
`, acc.ProjectName(), serviceName, userName)
}

func testAccKafkaUserWriteOnlyPassword(serviceName, userName string, version int) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "%[2]s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name        = aiven_kafka.bar.service_name
  project             = data.aiven_project.foo.project
  username            = "user-%[3]s"
  password_wo         = "WriteOnlyPass$%[4]d"
  password_wo_version = %[4]d
}
`, acc.ProjectName(), serviceName, userName, version)
}

func testAccKafkaUserWriteOnlyPasswordShort(serviceName, userName string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_kafka" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "%[2]s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_kafka_user" "foo" {
  service_name        = aiven_kafka.bar.service_name
  project             = data.aiven_project.foo.project
  username            = "user-%[3]s"
  password_wo         = "short"
  password_wo_version = 1
}
`, acc.ProjectName(), serviceName, userName)
}
