// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package connectionpool

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

/*
datasourceSchema:

	data "aiven_connection_pool" "example" {
	  project      = "foo"
	  service_name = "test"
	  pool_name    = "test"

	  // COMPUTED FIELDS
	  connection_uri = "foo"
	  database_name  = "test"
	  pool_mode      = "transaction"
	  pool_size      = 10
	  username       = "test"
	}
*/
func datasourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"connection_uri": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Connection URI for the DB pool.",
				Sensitive:           true,
			},
			"database_name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Service database name.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `project/service_name/pool_name`.",
			},
			"pool_mode": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "PGBouncer pool mode. The possible values are `session`, `statement` and `transaction`. The default value is `transaction`.",
			},
			"pool_name": schema.StringAttribute{
				MarkdownDescription: "PgBouncer connection pool name.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(63)},
			},
			"pool_size": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "Size of PGBouncer's PostgreSQL side connection pool. The default value is `10`.",
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project name.",
				Required:            true,
			},
			"service_name": schema.StringAttribute{
				MarkdownDescription: "Service name.",
				Required:            true,
			},
			"username": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Service username.",
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": timeouts.Block(ctx)},
		MarkdownDescription: "Gets information about a connection pool in an Aiven for PostgreSQL® service.",
	}
}
func datasourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"connection_uri": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"database_name": &adapter.Schema{Type: adapter.SchemaTypeString},
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"pool_mode": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"pool_name": &adapter.Schema{Type: adapter.SchemaTypeString},
			"pool_size": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeInt,
			},
			"project":      &adapter.Schema{Type: adapter.SchemaTypeString},
			"service_name": &adapter.Schema{Type: adapter.SchemaTypeString},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{"read": &adapter.Schema{Type: adapter.SchemaTypeString}},
				Type:       adapter.SchemaTypeObject,
			},
			"username": &adapter.Schema{Type: adapter.SchemaTypeString},
		},
		Type: adapter.SchemaTypeObject,
	}
}
