package valkey_test

import (
	"context"
	"errors"
	"fmt"
	"testing"

	"github.com/aiven/aiven-go-client/v2"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	acc "github.com/aiven/terraform-provider-aiven/internal/acctest"
	"github.com/aiven/terraform-provider-aiven/internal/schemautil"
)

func TestAccAivenValkeyUser_basic(t *testing.T) {
	resourceName := "aiven_valkey_user.foo"
	serviceName := acc.RandName("valkey")
	userName := acc.RandStr()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acc.TestAccPreCheck(t) },
		ProtoV6ProviderFactories: acc.TestProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckAivenValkeyUserResourceDestroy,
		Steps: []resource.TestStep{
			{
				// create with custom password
				Config: testAccValkeyUserValkeyACLResource(serviceName, userName, "acc-custom-Test$1234"),
				Check: resource.ComposeTestCheckFunc(
					schemautil.TestAccCheckAivenServiceUserAttributes("data.aiven_valkey_user.user"),
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-Test$1234"),
				),
			},
			{
				// update custom password
				Config: testAccValkeyUserValkeyACLResource(serviceName, userName, "acc-custom-UpdatedPass$123"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-UpdatedPass$123"),
				),
			},
			{
				// transition to auto-generated password
				Config: testAccValkeyUserAutoGenerated(serviceName, userName),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasGeneratedPassword(resourceName),
				),
			},
			{
				// back to custom password
				Config: testAccValkeyUserValkeyACLResource(serviceName, userName, "acc-custom-Optional$Pass123"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-Optional$Pass123"),
				),
			},
			{
				// transition to write-only password
				Config: testAccValkeyUserWriteOnly(serviceName, userName, 1),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasWOPassword(resourceName),
				),
			},
			{
				// rotate write-only password
				Config: testAccValkeyUserWriteOnly(serviceName, userName, 2),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasWOPassword(resourceName),
				),
			},
			{
				// transition back to auto-generated password
				Config: testAccValkeyUserAutoGenerated(serviceName, userName),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasGeneratedPassword(resourceName),
				),
			},
			{
				// final custom password
				Config: testAccValkeyUserValkeyACLResource(serviceName, userName, "acc-custom-FinalPass$456"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-FinalPass$456"),
				),
			},
		},
	})
}

func testAccCheckAivenValkeyUserResourceDestroy(s *terraform.State) error {
	c := acc.GetTestAivenClient()

	ctx := context.Background()

	// loop through the resources in state, verifying each aiven_valkey_user is destroyed
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "aiven_valkey_user" {
			continue
		}

		projectName, serviceName, username, err := schemautil.SplitResourceID3(rs.Primary.ID)
		if err != nil {
			return err
		}

		p, err := c.ServiceUsers.Get(ctx, projectName, serviceName, username)
		if err != nil {
			var e aiven.Error
			if errors.As(err, &e) && e.Status != 404 {
				return err
			}
		}

		if p != nil {
			return fmt.Errorf("common user (%s) still exists", rs.Primary.ID)
		}
	}

	return nil
}

func testAccValkeyUserValkeyACLResource(serviceName, userName, password string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_valkey" "bar" {
  project      = data.aiven_project.foo.project
  cloud_name   = "google-europe-west1"
  plan         = "startup-4"
  service_name = "%[2]s"
}

resource "aiven_valkey_user" "foo" {
  service_name = aiven_valkey.bar.service_name
  project      = aiven_valkey.bar.project
  username     = "user-%[3]s"
  password     = "%[4]s"

  valkey_acl_commands   = ["+set"]
  valkey_acl_keys       = ["prefix*", "another_key"]
  valkey_acl_categories = ["-@all", "+@admin"]
  valkey_acl_channels   = ["test"]

  depends_on = [aiven_valkey.bar]
}

data "aiven_valkey_user" "user" {
  service_name = aiven_valkey_user.foo.service_name
  project      = aiven_valkey_user.foo.project
  username     = aiven_valkey_user.foo.username

  depends_on = [aiven_valkey_user.foo]
}`, acc.ProjectName(), serviceName, userName, password)
}

func testAccValkeyUserAutoGenerated(serviceName, userName string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_valkey" "bar" {
  project      = data.aiven_project.foo.project
  cloud_name   = "google-europe-west1"
  plan         = "startup-4"
  service_name = "%[2]s"
}

resource "aiven_valkey_user" "foo" {
  service_name = aiven_valkey.bar.service_name
  project      = aiven_valkey.bar.project
  username     = "user-%[3]s"

  valkey_acl_commands   = ["+set"]
  valkey_acl_keys       = ["prefix*", "another_key"]
  valkey_acl_categories = ["-@all", "+@admin"]
  valkey_acl_channels   = ["test"]

  depends_on = [aiven_valkey.bar]
}

data "aiven_valkey_user" "user" {
  service_name = aiven_valkey_user.foo.service_name
  project      = aiven_valkey_user.foo.project
  username     = aiven_valkey_user.foo.username

  depends_on = [aiven_valkey_user.foo]
}`, acc.ProjectName(), serviceName, userName)
}

func testAccValkeyUserWriteOnly(serviceName, userName string, version int) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_valkey" "bar" {
  project      = data.aiven_project.foo.project
  cloud_name   = "google-europe-west1"
  plan         = "startup-4"
  service_name = "%[2]s"
}

resource "aiven_valkey_user" "foo" {
  service_name        = aiven_valkey.bar.service_name
  project             = aiven_valkey.bar.project
  username            = "user-%[3]s"
  password_wo         = "WriteOnlyPass$%[4]d"
  password_wo_version = %[4]d

  valkey_acl_commands   = ["+set"]
  valkey_acl_keys       = ["prefix*", "another_key"]
  valkey_acl_categories = ["-@all", "+@admin"]
  valkey_acl_channels   = ["test"]

  depends_on = [aiven_valkey.bar]
}

data "aiven_valkey_user" "user" {
  service_name = aiven_valkey_user.foo.service_name
  project      = aiven_valkey_user.foo.project
  username     = aiven_valkey_user.foo.username

  depends_on = [aiven_valkey_user.foo]
}`, acc.ProjectName(), serviceName, userName, version)
}
