// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package staticip

import (
	"context"
	"fmt"
	"net/http"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/aiven/go-client-codegen/handler/staticip"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

const typeName = "aiven_static_ip"

// idFields the ID attribute fields, i.e.:
// terraform import aiven_static_ip.foo PROJECT/STATIC_IP_ADDRESS_ID
func idFields() []string {
	return []string{"project", "static_ip_address_id"}
}

var ResourceOptions = adapter.ResourceOptions{
	Create:                createView,
	Delete:                deleteView,
	IDFields:              idFields(),
	Read:                  readView,
	RefreshState:          true,
	RefreshStateWaiter:    refreshStateWaiter,
	Schema:                resourceSchema,
	SchemaInternal:        resourceSchemaInternal(),
	TerminationProtection: true,
	TypeName:              typeName,
	Update:                updateView,
}

func createView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	req := new(staticip.StaticIPCreateIn)
	err := d.Expand(req)
	if err != nil {
		return err
	}
	rsp, err := client.StaticIPCreate(ctx, d.Get("project").(string), req)
	if err != nil {
		return err
	}
	return d.Flatten(rsp)
}

func readView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	rsp, err := client.StaticIPList(ctx, d.Get("project").(string))
	if err != nil {
		return err
	}
	found := adapter.FilterIndex(rsp, func(i int) bool {
		return rsp[i].StaticIPAddressId == d.Get("static_ip_address_id").(string)
	})
	switch len(found) {
	case 1:
		return d.Flatten(&found[0])
	case 0:
		return avngen.Error{
			Message:     "`aiven_static_ip` with given `static_ip_address_id` not found",
			OperationID: "StaticIPList",
			Status:      http.StatusNotFound,
		}
	default:
		return fmt.Errorf("found %d `aiven_static_ip` with given `static_ip_address_id`", len(found))
	}
}

func updateView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	req := new(staticip.ProjectStaticIPPatchIn)
	err := d.Expand(req)
	if err != nil {
		return err
	}
	rsp, err := client.ProjectStaticIPPatch(ctx, d.Get("project").(string), d.Get("static_ip_address_id").(string), req)
	if err != nil {
		return err
	}
	return d.Flatten(rsp)
}

func deleteView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	_, err := client.StaticIPDelete(ctx, d.Get("project").(string), d.Get("static_ip_address_id").(string))
	return err
}
