// Copyright (c) 2025 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package project

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/aiven/go-client-codegen/handler/organizationprojects"
	"github.com/hashicorp/terraform-plugin-framework/diag"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/errmsg"
)

var ResourceOptions = adapter.ResourceOptions[*resourceModel, tfModel]{
	Beta:         false,
	Create:       createView,
	Delete:       deleteView,
	IDFields:     idFields(),
	Read:         readView,
	RefreshState: true,
	Schema:       resourceSchema,
	TypeName:     typeName,
	Update:       updateView,
}

var DataSourceOptions = adapter.DataSourceOptions[*datasourceModel, tfModel]{
	Beta:     false,
	Read:     readView,
	Schema:   datasourceSchema,
	TypeName: typeName,
}

func createView(ctx context.Context, client avngen.Client, plan *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		var req organizationprojects.OrganizationProjectsCreateIn
		diags.Append(expandData(ctx, plan, nil, &req, expandModifier(ctx, client))...)
		if diags.HasError() {
			return
		}

		rsp, err := client.OrganizationProjectsCreate(ctx, plan.OrganizationID.ValueString(), &req)
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationProjectsCreate Error", err))
			return
		}
		diags.Append(flattenData(ctx, plan, rsp, flattenModifier(ctx, client))...)
	}()
	return diags
}

func readView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		rsp, err := client.OrganizationProjectsGet(ctx, state.OrganizationID.ValueString(), state.ProjectID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationProjectsGet Error", err))
			return
		}
		diags.Append(flattenData(ctx, state, rsp, flattenModifier(ctx, client))...)
	}()
	if diags.HasError() {
		return diags
	}
	func() {
		rsp, err := client.ProjectKmsGetCA(ctx, state.ProjectID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("ProjectKmsGetCA Error", err))
			return
		}
		diags.Append(flattenData(ctx, state, &map[string]any{"certificate": rsp}, flattenModifier(ctx, client))...)
	}()
	return diags
}

func updateView(ctx context.Context, client avngen.Client, plan, state, config *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		var req organizationprojects.OrganizationProjectsUpdateIn
		diags.Append(expandData(ctx, plan, state, &req, expandModifier(ctx, client))...)
		if diags.HasError() {
			return
		}

		rsp, err := client.OrganizationProjectsUpdate(ctx, state.OrganizationID.ValueString(), state.ProjectID.ValueString(), &req)
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationProjectsUpdate Error", err))
			return
		}
		diags.Append(flattenData(ctx, plan, rsp, flattenModifier(ctx, client))...)
	}()
	return diags
}

func deleteView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		err := client.OrganizationProjectsDelete(ctx, state.OrganizationID.ValueString(), state.ProjectID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationProjectsDelete Error", err))
			return
		}
	}()
	return diags
}
