// Copyright (c) 2025 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package unit

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// datasourceModel with specific datasource timeouts
type datasourceModel struct {
	tfModel
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

func (tf *datasourceModel) SharedModel() *tfModel {
	return &tf.tfModel
}

func (tf *datasourceModel) TimeoutsObject() types.Object {
	return tf.Timeouts.Object
}

/*
datasourceSchema:

	data "aiven_organizational_unit" "example" {
	  id = "foo"

	  // COMPUTED FIELDS
	  create_time = "foo"
	  name        = "test"
	  parent_id   = "foo"
	  tenant_id   = "foo"
	  update_time = "foo"
	}
*/
func datasourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"create_time": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Timestamp in ISO 8601 format, always in UTC.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The ID of this resource. Exactly one of the fields must be specified: `id` or `name`.",
				Optional:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(36)},
			},
			"name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The name of the organizational unit. Exactly one of the fields must be specified: `id` or `name`.",
				Optional:            true,
			},
			"parent_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The ID of the organization that the unit is created in.",
			},
			"tenant_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Tenant identifier.",
			},
			"update_time": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Timestamp in ISO 8601 format, always in UTC.",
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": timeouts.Block(ctx)},
		MarkdownDescription: "Gets information about an organizational unit.",
	}
}
