// Code generated by user config generator. DO NOT EDIT.

package influxdb

import (
	"context"
	"encoding/json"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/stretchr/testify/require"

	"github.com/aiven/terraform-provider-aiven/internal/schemautil"
)

const allFields = `{
    "additional_backup_regions": [
        "foo"
    ],
    "custom_domain": "foo",
    "influxdb": {
        "log_queries_after": 1,
        "max_connection_limit": 1,
        "max_row_limit": 1,
        "max_select_buckets": 1,
        "max_select_point": 1,
        "query_log_enabled": true,
        "query_timeout": 1
    },
    "ip_filter": [
        {
            "description": "foo",
            "network": "foo"
        }
    ],
    "private_access": {
        "influxdb": true
    },
    "privatelink_access": {
        "influxdb": true
    },
    "project_to_fork_from": "foo",
    "public_access": {
        "influxdb": true
    },
    "recovery_basebackup_name": "foo",
    "service_to_fork_from": "foo",
    "static_ips": true
}`
const updateOnlyFields = `{
    "additional_backup_regions": [
        "foo"
    ],
    "custom_domain": "foo",
    "influxdb": {
        "log_queries_after": 1,
        "max_connection_limit": 1,
        "max_row_limit": 1,
        "max_select_buckets": 1,
        "max_select_point": 1,
        "query_log_enabled": true,
        "query_timeout": 1
    },
    "ip_filter": [
        {
            "description": "foo",
            "network": "foo"
        }
    ],
    "private_access": {
        "influxdb": true
    },
    "privatelink_access": {
        "influxdb": true
    },
    "public_access": {
        "influxdb": true
    },
    "recovery_basebackup_name": "foo",
    "static_ips": true
}`

func TestUserConfig(t *testing.T) {
	cases := []struct {
		name   string
		source string
		expect string
		create bool
	}{
		{
			name:   "fields to create resource",
			source: allFields,
			expect: allFields,
			create: true,
		},
		{
			name:   "only fields to update resource",
			source: allFields,
			expect: updateOnlyFields, // usually, fewer fields
			create: false,
		},
	}

	ctx := context.Background()
	diags := make(diag.Diagnostics, 0)
	for _, opt := range cases {
		t.Run(opt.name, func(t *testing.T) {
			dto := new(dtoUserConfig)
			err := json.Unmarshal([]byte(opt.source), dto)
			require.NoError(t, err)

			// From json to TF
			tfo := flattenUserConfig(ctx, diags, dto)
			require.Empty(t, diags)

			// From TF to json
			config := expandUserConfig(ctx, diags, tfo)
			require.Empty(t, diags)

			// Run specific marshal (create or update resource)
			dtoConfig, err := schemautil.MarshalUserConfig(config, opt.create)
			require.NoError(t, err)

			// Compares that output is strictly equal to the input
			// If so, the flow is valid
			b, err := json.MarshalIndent(dtoConfig, "", "    ")
			require.NoError(t, err)
			require.Empty(t, cmp.Diff(opt.expect, string(b)))
		})
	}
}
