// Code generated by mockery v2.51.0. DO NOT EDIT.

package mocks

import (
	time "time"

	cty "github.com/hashicorp/go-cty/cty"
	mock "github.com/stretchr/testify/mock"
)

// MockResourceData is an autogenerated mock type for the ResourceData type
type MockResourceData struct {
	mock.Mock
}

type MockResourceData_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceData) EXPECT() *MockResourceData_Expecter {
	return &MockResourceData_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0
func (_m *MockResourceData) Get(_a0 string) any {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	if rf, ok := ret.Get(0).(func(string) any); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	return r0
}

// MockResourceData_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockResourceData_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 string
func (_e *MockResourceData_Expecter) Get(_a0 interface{}) *MockResourceData_Get_Call {
	return &MockResourceData_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *MockResourceData_Get_Call) Run(run func(_a0 string)) *MockResourceData_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockResourceData_Get_Call) Return(_a0 any) *MockResourceData_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceData_Get_Call) RunAndReturn(run func(string) any) *MockResourceData_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetOk provides a mock function with given fields: _a0
func (_m *MockResourceData) GetOk(_a0 string) (any, bool) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetOk")
	}

	var r0 any
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (any, bool)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) any); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockResourceData_GetOk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOk'
type MockResourceData_GetOk_Call struct {
	*mock.Call
}

// GetOk is a helper method to define mock.On call
//   - _a0 string
func (_e *MockResourceData_Expecter) GetOk(_a0 interface{}) *MockResourceData_GetOk_Call {
	return &MockResourceData_GetOk_Call{Call: _e.mock.On("GetOk", _a0)}
}

func (_c *MockResourceData_GetOk_Call) Run(run func(_a0 string)) *MockResourceData_GetOk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockResourceData_GetOk_Call) Return(_a0 any, _a1 bool) *MockResourceData_GetOk_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockResourceData_GetOk_Call) RunAndReturn(run func(string) (any, bool)) *MockResourceData_GetOk_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawConfig provides a mock function with no fields
func (_m *MockResourceData) GetRawConfig() cty.Value {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRawConfig")
	}

	var r0 cty.Value
	if rf, ok := ret.Get(0).(func() cty.Value); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(cty.Value)
	}

	return r0
}

// MockResourceData_GetRawConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawConfig'
type MockResourceData_GetRawConfig_Call struct {
	*mock.Call
}

// GetRawConfig is a helper method to define mock.On call
func (_e *MockResourceData_Expecter) GetRawConfig() *MockResourceData_GetRawConfig_Call {
	return &MockResourceData_GetRawConfig_Call{Call: _e.mock.On("GetRawConfig")}
}

func (_c *MockResourceData_GetRawConfig_Call) Run(run func()) *MockResourceData_GetRawConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResourceData_GetRawConfig_Call) Return(_a0 cty.Value) *MockResourceData_GetRawConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceData_GetRawConfig_Call) RunAndReturn(run func() cty.Value) *MockResourceData_GetRawConfig_Call {
	_c.Call.Return(run)
	return _c
}

// HasChange provides a mock function with given fields: _a0
func (_m *MockResourceData) HasChange(_a0 string) bool {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for HasChange")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockResourceData_HasChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasChange'
type MockResourceData_HasChange_Call struct {
	*mock.Call
}

// HasChange is a helper method to define mock.On call
//   - _a0 string
func (_e *MockResourceData_Expecter) HasChange(_a0 interface{}) *MockResourceData_HasChange_Call {
	return &MockResourceData_HasChange_Call{Call: _e.mock.On("HasChange", _a0)}
}

func (_c *MockResourceData_HasChange_Call) Run(run func(_a0 string)) *MockResourceData_HasChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockResourceData_HasChange_Call) Return(_a0 bool) *MockResourceData_HasChange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceData_HasChange_Call) RunAndReturn(run func(string) bool) *MockResourceData_HasChange_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function with no fields
func (_m *MockResourceData) Id() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockResourceData_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type MockResourceData_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *MockResourceData_Expecter) Id() *MockResourceData_Id_Call {
	return &MockResourceData_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *MockResourceData_Id_Call) Run(run func()) *MockResourceData_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResourceData_Id_Call) Return(_a0 string) *MockResourceData_Id_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceData_Id_Call) RunAndReturn(run func() string) *MockResourceData_Id_Call {
	_c.Call.Return(run)
	return _c
}

// IsNewResource provides a mock function with no fields
func (_m *MockResourceData) IsNewResource() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsNewResource")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockResourceData_IsNewResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsNewResource'
type MockResourceData_IsNewResource_Call struct {
	*mock.Call
}

// IsNewResource is a helper method to define mock.On call
func (_e *MockResourceData_Expecter) IsNewResource() *MockResourceData_IsNewResource_Call {
	return &MockResourceData_IsNewResource_Call{Call: _e.mock.On("IsNewResource")}
}

func (_c *MockResourceData_IsNewResource_Call) Run(run func()) *MockResourceData_IsNewResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockResourceData_IsNewResource_Call) Return(_a0 bool) *MockResourceData_IsNewResource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceData_IsNewResource_Call) RunAndReturn(run func() bool) *MockResourceData_IsNewResource_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: _a0, _a1
func (_m *MockResourceData) Set(_a0 string, _a1 any) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResourceData_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockResourceData_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - _a0 string
//   - _a1 any
func (_e *MockResourceData_Expecter) Set(_a0 interface{}, _a1 interface{}) *MockResourceData_Set_Call {
	return &MockResourceData_Set_Call{Call: _e.mock.On("Set", _a0, _a1)}
}

func (_c *MockResourceData_Set_Call) Run(run func(_a0 string, _a1 any)) *MockResourceData_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(any))
	})
	return _c
}

func (_c *MockResourceData_Set_Call) Return(_a0 error) *MockResourceData_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceData_Set_Call) RunAndReturn(run func(string, any) error) *MockResourceData_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetId provides a mock function with given fields: _a0
func (_m *MockResourceData) SetId(_a0 string) {
	_m.Called(_a0)
}

// MockResourceData_SetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetId'
type MockResourceData_SetId_Call struct {
	*mock.Call
}

// SetId is a helper method to define mock.On call
//   - _a0 string
func (_e *MockResourceData_Expecter) SetId(_a0 interface{}) *MockResourceData_SetId_Call {
	return &MockResourceData_SetId_Call{Call: _e.mock.On("SetId", _a0)}
}

func (_c *MockResourceData_SetId_Call) Run(run func(_a0 string)) *MockResourceData_SetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockResourceData_SetId_Call) Return() *MockResourceData_SetId_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockResourceData_SetId_Call) RunAndReturn(run func(string)) *MockResourceData_SetId_Call {
	_c.Run(run)
	return _c
}

// Timeout provides a mock function with given fields: _a0
func (_m *MockResourceData) Timeout(_a0 string) time.Duration {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Timeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(string) time.Duration); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockResourceData_Timeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Timeout'
type MockResourceData_Timeout_Call struct {
	*mock.Call
}

// Timeout is a helper method to define mock.On call
//   - _a0 string
func (_e *MockResourceData_Expecter) Timeout(_a0 interface{}) *MockResourceData_Timeout_Call {
	return &MockResourceData_Timeout_Call{Call: _e.mock.On("Timeout", _a0)}
}

func (_c *MockResourceData_Timeout_Call) Run(run func(_a0 string)) *MockResourceData_Timeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockResourceData_Timeout_Call) Return(_a0 time.Duration) *MockResourceData_Timeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResourceData_Timeout_Call) RunAndReturn(run func(string) time.Duration) *MockResourceData_Timeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResourceData creates a new instance of MockResourceData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceData(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceData {
	mock := &MockResourceData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
