// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package topic

import "github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"

const typeName = "aiven_kafka_topic"

// idFields the ID attribute fields, i.e.:
// terraform import aiven_kafka_topic.foo PROJECT/SERVICE_NAME/TOPIC_NAME
func idFields() []string {
	return []string{"project", "service_name", "topic_name"}
}

var ResourceOptions = adapter.ResourceOptions{
	Create:                createView,
	Delete:                deleteView,
	IDFields:              idFields(),
	ModifyPlan:            modifyPlan,
	Read:                  readView,
	RemoveMissing:         true,
	Schema:                resourceSchema,
	SchemaInternal:        resourceSchemaInternal(),
	TerminationProtection: true,
	TypeName:              typeName,
	Update:                updateView,
	ValidateConfig:        validateConfig,
}

var DataSourceOptions = adapter.DataSourceOptions{
	IDFields:       idFields(),
	Read:           readView,
	Schema:         datasourceSchema,
	SchemaInternal: datasourceSchemaInternal(),
	TypeName:       typeName,
}
