// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package azure

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

const typeName = "aiven_cmk_accessor_azure"

// idFields the ID attribute fields, i.e.:
// terraform import aiven_cmk_accessor_azure.foo PROJECT
func idFields() []string {
	return []string{"project"}
}

var DataSourceOptions = adapter.DataSourceOptions{
	IDFields:       idFields(),
	Read:           readView,
	Schema:         datasourceSchema,
	SchemaInternal: datasourceSchemaInternal(),
	TypeName:       typeName,
}

func readView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	rsp, err := client.CMKAccessorsList(ctx, d.Get("project").(string))
	if err != nil {
		return err
	}
	return d.Flatten(rsp.Azure)
}
