components:
  schemas:
    OrganizationBillingGroupCreateRequestBody: &billingGroup
      # Turns email fields into an arrays of strings
      properties:
        billing_emails:
          items:
            type: string
        billing_contact_emails:
          items:
            type: string
    OrganizationBillingGroupCreateResponse: *billingGroup
    OrganizationBillingGroupGetRequestBody: *billingGroup
    OrganizationBillingGroupGetResponse: *billingGroup
    OrganizationBillingGroupUpdateRequestBody: *billingGroup
    OrganizationBillingGroupUpdateResponse: *billingGroup
    OrganizationBillingGroupListResponse:
      properties:
        billing_groups:
          items: *billingGroup
    OrganizationProjectsCreateRequestBody: &orgProjProperties
      properties:
        tags:
          description: Tags are key-value pairs that allow you to categorize projects.
          type: array
          items:
            type: object
            required: [key, value]
            properties:
              key:
                type: string
                description: "Project tag key"
              value:
                type: string
                description: "Project tag value"
        tech_emails:
          items:
            type: string
          description: |
            The email addresses for [project contacts](https://aiven.io/docs/platform/howto/technical-emails),
            who will receive important alerts and updates about this project and its services. 
            You can also set email contacts at the service level.
            It's good practice to keep these up-to-date to be aware of any potential issues with your project
    OrganizationProjectsUpdateRequestBody: *orgProjProperties
    OrganizationProjectsCreateResponse: *orgProjProperties
    OrganizationProjectsUpdateResponse: *orgProjProperties
    OrganizationProjectsGetResponse: *orgProjProperties
