// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package applicationuser

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/aiven/go-client-codegen/handler/applicationuser"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

const typeName = "aiven_organization_application_user"

// idFields the ID attribute fields, i.e.:
// terraform import aiven_organization_application_user.foo ORGANIZATION_ID/USER_ID
func idFields() []string {
	return []string{"organization_id", "user_id"}
}

var ResourceOptions = adapter.ResourceOptions{
	Create:         createView,
	Delete:         deleteView,
	IDFields:       idFields(),
	Read:           readView,
	Schema:         resourceSchema,
	SchemaInternal: resourceSchemaInternal(),
	TypeName:       typeName,
	Update:         updateView,
}

var DataSourceOptions = adapter.DataSourceOptions{
	IDFields:       idFields(),
	Read:           readView,
	Schema:         datasourceSchema,
	SchemaInternal: datasourceSchemaInternal(),
	TypeName:       typeName,
}

func createView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	req := new(applicationuser.ApplicationUserCreateIn)
	err := d.Expand(req)
	if err != nil {
		return err
	}
	rsp, err := client.ApplicationUserCreate(ctx, d.Get("organization_id").(string), req)
	if err != nil {
		return err
	}
	return d.Flatten(rsp, adapter.RenameFields(map[string]string{"user_email": "email"}))
}

func readView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	rsp, err := client.ApplicationUserGet(ctx, d.Get("organization_id").(string), d.Get("user_id").(string))
	if err != nil {
		return err
	}
	return d.Flatten(rsp, adapter.RenameFields(map[string]string{"user_email": "email"}))
}

func updateView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	req := new(applicationuser.ApplicationUserUpdateIn)
	err := d.Expand(req)
	if err != nil {
		return err
	}
	rsp, err := client.ApplicationUserUpdate(ctx, d.Get("organization_id").(string), d.Get("user_id").(string), req)
	if err != nil {
		return err
	}
	return d.Flatten(rsp, adapter.RenameFields(map[string]string{"user_email": "email"}))
}

func deleteView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	return client.ApplicationUserDelete(ctx, d.Get("organization_id").(string), d.Get("user_id").(string))
}
