// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package connectionpool

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/legacytimeouts"
)

func resourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"connection_uri": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Connection URI for the DB pool.",
				Sensitive:           true,
			},
			"database_name": schema.StringAttribute{
				MarkdownDescription: "Service database name. Maximum length: `63`. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(63)},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `project/service_name/pool_name`.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"pool_mode": schema.StringAttribute{
				Computed:            true,
				Default:             stringdefault.StaticString("transaction"),
				MarkdownDescription: "PGBouncer pool mode. The possible values are `session`, `statement` and `transaction`. The default value is `transaction`.",
				Optional:            true,
				Validators:          []validator.String{stringvalidator.OneOf("session", "statement", "transaction")},
			},
			"pool_name": schema.StringAttribute{
				MarkdownDescription: "PgBouncer connection pool name. Maximum length: `63`. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(63)},
			},
			"pool_size": schema.Int64Attribute{
				Computed:            true,
				Default:             int64default.StaticInt64(10.0),
				MarkdownDescription: "Size of PGBouncer's PostgreSQL side connection pool. Value must be between `1` and `10000`. The default value is `10`.",
				Optional:            true,
				Validators:          []validator.Int64{int64validator.Between(1, 10000)},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"service_name": schema.StringAttribute{
				MarkdownDescription: "Service name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"username": schema.StringAttribute{
				MarkdownDescription: "Service username. Length must be between `1` and `64`.",
				Optional:            true,
				Validators:          []validator.String{stringvalidator.LengthBetween(1, 64)},
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": legacytimeouts.BlockAll(ctx)},
		MarkdownDescription: "Creates and manages a [connection pool](https://aiven.io/docs/products/postgresql/concepts/pg-connection-pooling) in an Aiven for PostgreSQL® service. If this resource is missing (for example, after a service power off), it's removed from the state and a new create plan is generated.",
	}
}
func resourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"connection_uri": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"database_name": &adapter.Schema{Type: adapter.SchemaTypeString},
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"pool_mode": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"pool_name": &adapter.Schema{Type: adapter.SchemaTypeString},
			"pool_size": &adapter.Schema{
				Computed:       true,
				Type:           adapter.SchemaTypeInt,
				ZeroNotAllowed: true,
			},
			"project":      &adapter.Schema{Type: adapter.SchemaTypeString},
			"service_name": &adapter.Schema{Type: adapter.SchemaTypeString},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{
					"create":  &adapter.Schema{Type: adapter.SchemaTypeString},
					"default": &adapter.Schema{Type: adapter.SchemaTypeString},
					"delete":  &adapter.Schema{Type: adapter.SchemaTypeString},
					"read":    &adapter.Schema{Type: adapter.SchemaTypeString},
					"update":  &adapter.Schema{Type: adapter.SchemaTypeString},
				},
				Type: adapter.SchemaTypeObject,
			},
			"username": &adapter.Schema{
				Type:           adapter.SchemaTypeString,
				ZeroNotAllowed: true,
			},
		},
		Type: adapter.SchemaTypeObject,
	}
}
