terraform import aiven_transit_gateway_vpc_attachment.example PROJECT/VPC_ID/PEER_CLOUD_ACCOUNT/PEER_VPC
terraform import aiven_transit_gateway_vpc_attachment.example PROJECT/VPC_ID/PEER_CLOUD_ACCOUNT/PEER_VPC/PEER_REGION
