// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package azureorgvpcpeeringconnection

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

func datasourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"azure_subscription_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the Azure subscription in UUID4 format.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(1024)},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `organization_id/organization_vpc_id/azure_subscription_id/vnet_name/peer_resource_group`.",
			},
			"organization_id": schema.StringAttribute{
				MarkdownDescription: "ID of an organization.",
				Required:            true,
			},
			"organization_vpc_id": schema.StringAttribute{
				MarkdownDescription: "Organization VPC ID.",
				Required:            true,
			},
			"peer_azure_app_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The ID of the Azure app that is allowed to create a peering to the Azure Virtual Network (VNet) in UUID4 format.",
			},
			"peer_azure_tenant_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The Azure tenant ID in UUID4 format.",
			},
			"peer_resource_group": schema.StringAttribute{
				MarkdownDescription: "The name of the Azure resource group associated with the VNet.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(1024)},
			},
			"peering_connection_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Organization peering connection ID.",
			},
			"state": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "State of the peering connection. The possible values are `ACTIVE`, `APPROVED`, `APPROVED_PEER_REQUESTED`, `DELETED`, `DELETED_BY_PEER`, `DELETING`, `ERROR`, `INVALID_SPECIFICATION`, `PENDING_PEER` and `REJECTED_BY_PEER`.",
			},
			"vnet_name": schema.StringAttribute{
				MarkdownDescription: "The name of the Azure VNet.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(1024)},
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": timeouts.Block(ctx)},
		MarkdownDescription: "Gets information about an Azure VPC peering connection.",
	}
}
func datasourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"azure_subscription_id": &adapter.Schema{Type: adapter.SchemaTypeString},
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"organization_id":     &adapter.Schema{Type: adapter.SchemaTypeString},
			"organization_vpc_id": &adapter.Schema{Type: adapter.SchemaTypeString},
			"peer_azure_app_id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"peer_azure_tenant_id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"peer_resource_group": &adapter.Schema{Type: adapter.SchemaTypeString},
			"peering_connection_id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"state": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{"read": &adapter.Schema{Type: adapter.SchemaTypeString}},
				Type:       adapter.SchemaTypeObject,
			},
			"vnet_name": &adapter.Schema{Type: adapter.SchemaTypeString},
		},
		Type: adapter.SchemaTypeObject,
	}
}
