// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package user

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/legacytimeouts"
)

/*
resourceSchema:

	resource "aiven_opensearch_user" "example" {
	  project             = "foo" // Force new
	  service_name        = "test" // Force new
	  username            = "test" // Force new
	  password            = "password"
	  password_wo         = "password"
	  password_wo_version = 42

	  // COMPUTED FIELDS
	  type = "foo"
	}
*/
func resourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `project/service_name/username`.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"password": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The password of the service user (auto-generated if not provided). The field conflicts with `password_wo`. Value must be between `8` and `256`.",
				Optional:            true,
				Sensitive:           true,
				Validators:          []validator.String{stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("password_wo"))},
			},
			"password_wo": schema.StringAttribute{
				MarkdownDescription: "The password of the service user (write-only, not stored in state). The field is required with `password_wo_version`. The field conflicts with `password`. Value must be between `8` and `256`.",
				Optional:            true,
				Sensitive:           true,
				Validators:          []validator.String{stringvalidator.AlsoRequires(path.MatchRelative().AtParent().AtName("password_wo_version")), stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("password"))},
				WriteOnly:           true,
			},
			"password_wo_version": schema.Int64Attribute{
				MarkdownDescription: "Version number for `password_wo`. Increment this to rotate the password. Must be >= 1. The field is required with `password_wo`. Minimum value: `1`.",
				Optional:            true,
				Validators:          []validator.Int64{int64validator.AtLeast(1), int64validator.AlsoRequires(path.MatchRelative().AtParent().AtName("password_wo"))},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"service_name": schema.StringAttribute{
				MarkdownDescription: "Service name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"type": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Account type.",
			},
			"username": schema.StringAttribute{
				MarkdownDescription: "Account username. Maximum length: `64`. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(64)},
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": legacytimeouts.BlockAll(ctx)},
		MarkdownDescription: "Creates and manages an Aiven for OpenSearch® service user. If this resource is missing (for example, after a service power off), it's removed from the state and a new create plan is generated.",
	}
}
func resourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"password": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"password_wo":         &adapter.Schema{Type: adapter.SchemaTypeString},
			"password_wo_version": &adapter.Schema{Type: adapter.SchemaTypeInt},
			"project":             &adapter.Schema{Type: adapter.SchemaTypeString},
			"service_name":        &adapter.Schema{Type: adapter.SchemaTypeString},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{
					"create":  &adapter.Schema{Type: adapter.SchemaTypeString},
					"default": &adapter.Schema{Type: adapter.SchemaTypeString},
					"delete":  &adapter.Schema{Type: adapter.SchemaTypeString},
					"read":    &adapter.Schema{Type: adapter.SchemaTypeString},
					"update":  &adapter.Schema{Type: adapter.SchemaTypeString},
				},
				Type: adapter.SchemaTypeObject,
			},
			"type": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"username": &adapter.Schema{Type: adapter.SchemaTypeString},
		},
		Type: adapter.SchemaTypeObject,
	}
}
