// Code generated by user config generator. DO NOT EDIT.

package serviceintegrationendpoint

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	"github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/diff"
)

func externalAwsCloudwatchLogsUserConfig() *schema.Schema {
	return &schema.Schema{
		Description:      "ExternalAwsCloudwatchLogs user configurable settings",
		DiffSuppressFunc: diff.SuppressUnchanged,
		Elem: &schema.Resource{Schema: map[string]*schema.Schema{
			"access_key": {
				Description: "AWS access key. Required permissions are logs:CreateLogGroup, logs:CreateLogStream, logs:PutLogEvents and logs:DescribeLogStreams. Example: `AAAAAAAAAAAAAAAAAAAA`.",
				Required:    true,
				Sensitive:   true,
				Type:        schema.TypeString,
			},
			"log_group_name": {
				Description: "AWS CloudWatch log group name. Example: `my-log-group`.",
				Optional:    true,
				Type:        schema.TypeString,
			},
			"region": {
				Description: "AWS region. Example: `us-east-1`.",
				Required:    true,
				Type:        schema.TypeString,
			},
			"secret_key": {
				Description: "AWS secret key. Example: `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`.",
				Required:    true,
				Sensitive:   true,
				Type:        schema.TypeString,
			},
		}},
		MaxItems: 1,
		Optional: true,
		Type:     schema.TypeList,
	}
}
