// Code generated by user config generator. DO NOT EDIT.

package serviceintegrationendpoint

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"

	"github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/diff"
)

func externalPostgresqlUserConfig() *schema.Schema {
	return &schema.Schema{
		Description:      "ExternalPostgresql user configurable settings",
		DiffSuppressFunc: diff.SuppressUnchanged,
		Elem: &schema.Resource{Schema: map[string]*schema.Schema{
			"host": {
				Description: "Hostname or IP address of the server.",
				Required:    true,
				Type:        schema.TypeString,
			},
			"password": {
				Description: "Password.",
				Optional:    true,
				Sensitive:   true,
				Type:        schema.TypeString,
			},
			"port": {
				Description: "Port number of the server.",
				Required:    true,
				Type:        schema.TypeInt,
			},
			"ssl_client_certificate": {
				Description: "Client certificate.",
				Optional:    true,
				Type:        schema.TypeString,
			},
			"ssl_client_key": {
				Description: "Client key.",
				Optional:    true,
				Type:        schema.TypeString,
			},
			"ssl_mode": {
				Description:  "SSL Mode. The default value is `verify-full`.",
				Optional:     true,
				Type:         schema.TypeString,
				ValidateFunc: validation.StringInSlice([]string{"disable", "allow", "prefer", "require", "verify-ca", "verify-full"}, false),
			},
			"ssl_root_cert": {
				Description: "SSL Root Cert.",
				Optional:    true,
				Type:        schema.TypeString,
			},
			"username": {
				Description: "User name.",
				Required:    true,
				Type:        schema.TypeString,
			},
		}},
		MaxItems: 1,
		Optional: true,
		Type:     schema.TypeList,
	}
}
