// Code generated by user config generator. DO NOT EDIT.

package serviceintegrationendpoint

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	"github.com/aiven/terraform-provider-aiven/internal/sdkprovider/userconfig/diff"
)

func jolokiaUserConfig() *schema.Schema {
	return &schema.Schema{
		Description:      "Jolokia user configurable settings. **Warning:** There's no way to reset advanced configuration options to default. Options that you add cannot be removed later",
		DiffSuppressFunc: diff.SuppressUnchanged,
		Elem: &schema.Resource{Schema: map[string]*schema.Schema{
			"basic_auth_password": {
				Description: "Jolokia basic authentication password. Example: `yhfBNFii4C`.",
				Optional:    true,
				Sensitive:   true,
				Type:        schema.TypeString,
			},
			"basic_auth_username": {
				Description: "Jolokia basic authentication username. Example: `jol48k51`.",
				Optional:    true,
				Type:        schema.TypeString,
			},
		}},
		MaxItems: 1,
		Optional: true,
		Type:     schema.TypeList,
	}
}
