package opensearch_test

import (
	"context"
	"fmt"
	"testing"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	acc "github.com/aiven/terraform-provider-aiven/internal/acctest"
	"github.com/aiven/terraform-provider-aiven/internal/schemautil"
)

// openSearchTestPassword is the password used for the OpenSearch tests.
const openSearchTestPassword = "acc-custom-ThisIsATest123^=^"

func TestAccAivenOpenSearchUser_basic(t *testing.T) {
	resourceName := "aiven_opensearch_user.foo"
	serviceName := acc.RandName("opensearch")
	userName := acc.RandStr()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:                 func() { acc.TestAccPreCheck(t) },
		ProtoV6ProviderFactories: acc.TestProtoV6ProviderFactories,
		CheckDestroy:             testAccCheckAivenOpenSearchUserResourceDestroy,
		Steps: []resource.TestStep{
			{
				// create with custom password
				Config: testAccOpenSearchUserResource(serviceName, userName, openSearchTestPassword),
				Check: resource.ComposeTestCheckFunc(
					schemautil.TestAccCheckAivenServiceUserAttributes("data.aiven_opensearch_user.user"),
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasCustomPassword(resourceName, openSearchTestPassword),
				),
			},
			{
				// update custom password
				Config: testAccOpenSearchUserResource(serviceName, userName, "acc-custom-UpdatedPass$123"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-UpdatedPass$123"),
				),
			},
			{
				// transition to auto-generated password
				Config: testAccOpenSearchUserAutoGenerated(serviceName, userName),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasGeneratedPassword(resourceName),
				),
			},
			{
				// back to custom password
				Config: testAccOpenSearchUserResource(serviceName, userName, "acc-custom-Optional$Pass123"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-Optional$Pass123"),
				),
			},
			{
				// transition to write-only password
				Config: testAccOpenSearchUserWriteOnly(serviceName, userName, 1),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasWOPassword(resourceName),
				),
			},
			{
				// rotate write-only password
				Config: testAccOpenSearchUserWriteOnly(serviceName, userName, 2),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasWOPassword(resourceName),
				),
			},
			{
				// transition back to auto-generated password
				Config: testAccOpenSearchUserAutoGenerated(serviceName, userName),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasGeneratedPassword(resourceName),
				),
			},
			{
				// final custom password
				Config: testAccOpenSearchUserResource(serviceName, userName, "acc-custom-FinalPass$456"),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(resourceName, "service_name", serviceName),
					resource.TestCheckResourceAttr(resourceName, "project", acc.ProjectName()),
					resource.TestCheckResourceAttr(resourceName, "username", fmt.Sprintf("user-%s", userName)),
					acc.TestAccPasswordHasCustomPassword(resourceName, "acc-custom-FinalPass$456"),
				),
			},
		},
	})
}

func testAccCheckAivenOpenSearchUserResourceDestroy(s *terraform.State) error {
	c, err := acc.GetTestGenAivenClient()
	if err != nil {
		return fmt.Errorf("error instantiating client: %w", err)
	}

	ctx := context.Background()

	// loop through the resources in state, verifying each aiven_opensearch_user is destroyed
	for _, rs := range s.RootModule().Resources {
		if rs.Type != "aiven_opensearch_user" {
			continue
		}

		projectName, serviceName, username, err := schemautil.SplitResourceID3(rs.Primary.ID)
		if err != nil {
			return err
		}

		_, err = c.ServiceUserGet(ctx, projectName, serviceName, username)
		if err != nil && !avngen.IsNotFound(err) {
			return fmt.Errorf("error checking if user was destroyed: %w", err)
		}

		if err == nil {
			return fmt.Errorf("opensearch user (%s) still exists", rs.Primary.ID)
		}
	}

	return nil
}

func testAccOpenSearchUserResource(serviceName, userName, password string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_opensearch" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "%[2]s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_opensearch_user" "foo" {
  service_name = aiven_opensearch.bar.service_name
  project      = data.aiven_project.foo.project
  username     = "user-%[3]s"
  password     = "%[4]s"
}

data "aiven_opensearch_user" "user" {
  service_name = aiven_opensearch_user.foo.service_name
  project      = aiven_opensearch_user.foo.project
  username     = aiven_opensearch_user.foo.username
}`, acc.ProjectName(), serviceName, userName, password)
}

func testAccOpenSearchUserAutoGenerated(serviceName, userName string) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_opensearch" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "%[2]s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_opensearch_user" "foo" {
  service_name = aiven_opensearch.bar.service_name
  project      = data.aiven_project.foo.project
  username     = "user-%[3]s"
}

data "aiven_opensearch_user" "user" {
  service_name = aiven_opensearch_user.foo.service_name
  project      = aiven_opensearch_user.foo.project
  username     = aiven_opensearch_user.foo.username
}`, acc.ProjectName(), serviceName, userName)
}

func testAccOpenSearchUserWriteOnly(serviceName, userName string, version int) string {
	return fmt.Sprintf(`
data "aiven_project" "foo" {
  project = "%[1]s"
}

resource "aiven_opensearch" "bar" {
  project                 = data.aiven_project.foo.project
  cloud_name              = "google-europe-west1"
  plan                    = "startup-4"
  service_name            = "%[2]s"
  maintenance_window_dow  = "monday"
  maintenance_window_time = "10:00:00"
}

resource "aiven_opensearch_user" "foo" {
  service_name        = aiven_opensearch.bar.service_name
  project             = data.aiven_project.foo.project
  username            = "user-%[3]s"
  password_wo         = "WriteOnlyPass$%[4]d"
  password_wo_version = %[4]d
}

data "aiven_opensearch_user" "user" {
  service_name = aiven_opensearch_user.foo.service_name
  project      = aiven_opensearch_user.foo.project
  username     = aiven_opensearch_user.foo.username
}`, acc.ProjectName(), serviceName, userName, version)
}
