// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package access

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/aiven/go-client-codegen/handler/organizationgovernance"
	"github.com/hashicorp/terraform-plugin-framework/diag"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/errmsg"
)

var ResourceOptions = adapter.ResourceOptions[*resourceModel, tfModel]{
	Beta:     true,
	Create:   createView,
	Delete:   deleteView,
	IDFields: idFields(),
	Read:     readView,
	Schema:   resourceSchema,
	TypeName: typeName,
}

func createView(ctx context.Context, client avngen.Client, plan, config *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		var req organizationgovernance.OrganizationGovernanceAccessCreateIn
		diags.Append(expandData(ctx, plan, nil, &req)...)
		if diags.HasError() {
			return
		}

		rsp, err := client.OrganizationGovernanceAccessCreate(ctx, plan.OrganizationID.ValueString(), &req)
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationGovernanceAccessCreate Error", err))
			return
		}
		diags.Append(flattenData(ctx, plan, rsp)...)
	}()
	return diags
}

func readView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		rsp, err := client.OrganizationGovernanceAccessGet(ctx, state.OrganizationID.ValueString(), state.SusbcriptionID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationGovernanceAccessGet Error", err))
			return
		}
		diags.Append(flattenData(ctx, state, rsp)...)
	}()
	return diags
}

func deleteView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		_, err := client.OrganizationGovernanceAccessDelete(ctx, state.OrganizationID.ValueString(), state.SusbcriptionID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationGovernanceAccessDelete Error", err))
			return
		}
	}()
	return diags
}
