// Code generated by gojson. DO NOT EDIT.

package schema

type IntegrationTypes struct {
	ClickhouseKafka struct {
		Properties struct {
			Tables struct {
				Default []interface{} `yaml:"default"`
				Items   struct {
					Properties struct {
						Columns struct {
							Default []interface{} `yaml:"default"`
							Items   struct {
								Properties struct {
									Name struct {
										Example   string `yaml:"example"`
										MaxLength int    `yaml:"max_length"`
										MinLength int    `yaml:"min_length"`
										Title     string `yaml:"title"`
										Type      string `yaml:"type"`
									} `yaml:"name"`
									Type struct {
										Example   string `yaml:"example"`
										MaxLength int    `yaml:"max_length"`
										MinLength int    `yaml:"min_length"`
										Title     string `yaml:"title"`
										Type      string `yaml:"type"`
									} `yaml:"type"`
								} `yaml:"properties"`
								Title string `yaml:"title"`
								Type  string `yaml:"type"`
							} `yaml:"items"`
							MaxItems int    `yaml:"maxItems"`
							Title    string `yaml:"title"`
							Type     string `yaml:"type"`
						} `yaml:"columns"`
						DataFormat struct {
							Default string `yaml:"default"`
							Enum    []struct {
								Value string `yaml:"value"`
							} `yaml:"enum"`
							Example string `yaml:"example"`
							Title   string `yaml:"title"`
							Type    string `yaml:"type"`
						} `yaml:"data_format"`
						GroupName struct {
							Default   string `yaml:"default"`
							Example   string `yaml:"example"`
							MaxLength int    `yaml:"max_length"`
							MinLength int    `yaml:"min_length"`
							Title     string `yaml:"title"`
							Type      string `yaml:"type"`
						} `yaml:"group_name"`
						Name struct {
							Example   string `yaml:"example"`
							MaxLength int    `yaml:"max_length"`
							MinLength int    `yaml:"min_length"`
							Title     string `yaml:"title"`
							Type      string `yaml:"type"`
						} `yaml:"name"`
						Topics struct {
							Items struct {
								Properties struct {
									Name struct {
										Example   string `yaml:"example"`
										MaxLength int    `yaml:"max_length"`
										MinLength int    `yaml:"min_length"`
										Title     string `yaml:"title"`
										Type      string `yaml:"type"`
									} `yaml:"name"`
								} `yaml:"properties"`
								Title string `yaml:"title"`
								Type  string `yaml:"type"`
							} `yaml:"items"`
							MaxItems int    `yaml:"maxItems"`
							Title    string `yaml:"title"`
							Type     string `yaml:"type"`
						} `yaml:"topics"`
					} `yaml:"properties"`
					Title string `yaml:"title"`
					Type  string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"tables"`
		} `yaml:"properties"`
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"clickhouse_kafka"`
	ClickhousePostgresql struct {
		Properties struct {
			Databases struct {
				Default []struct {
					Database string `yaml:"database"`
					Schema   string `yaml:"schema"`
				} `yaml:"default"`
				Items struct {
					Properties struct {
						Database struct {
							Default   string `yaml:"default"`
							Example   string `yaml:"example"`
							MaxLength int    `yaml:"max_length"`
							MinLength int    `yaml:"min_length"`
							Title     string `yaml:"title"`
							Type      string `yaml:"type"`
						} `yaml:"database"`
						Schema struct {
							Default   string `yaml:"default"`
							Example   string `yaml:"example"`
							MaxLength int    `yaml:"max_length"`
							MinLength int    `yaml:"min_length"`
							Title     string `yaml:"title"`
							Type      string `yaml:"type"`
						} `yaml:"schema"`
					} `yaml:"properties"`
					Title string `yaml:"title"`
					Type  string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"databases"`
		} `yaml:"properties"`
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"clickhouse_postgresql"`
	Dashboard struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"dashboard"`
	Datadog struct {
		Properties struct {
			DatadogTags struct {
				Example []struct {
					Comment string `yaml:"comment"`
					Tag     string `yaml:"tag"`
				} `yaml:"example"`
				Items struct {
					Properties struct {
						Comment struct {
							Example   string `yaml:"example"`
							MaxLength int    `yaml:"max_length"`
							Title     string `yaml:"title"`
							Type      string `yaml:"type"`
						} `yaml:"comment"`
						Tag struct {
							Description string `yaml:"description"`
							Example     string `yaml:"example"`
							MaxLength   int    `yaml:"max_length"`
							MinLength   int    `yaml:"min_length"`
							Pattern     string `yaml:"pattern"`
							Title       string `yaml:"title"`
							Type        string `yaml:"type"`
							UserError   string `yaml:"user_error"`
						} `yaml:"tag"`
					} `yaml:"properties"`
					Title string `yaml:"title"`
					Type  string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"datadog_tags"`
			ExcludeConsumerGroups struct {
				Items struct {
					Example   string `yaml:"example"`
					MaxLength int    `yaml:"max_length"`
					Title     string `yaml:"title"`
					Type      string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"exclude_consumer_groups"`
			ExcludeTopics struct {
				Items struct {
					Example   string `yaml:"example"`
					MaxLength int    `yaml:"max_length"`
					Title     string `yaml:"title"`
					Type      string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"exclude_topics"`
			IncludeConsumerGroups struct {
				Items struct {
					Example   string `yaml:"example"`
					MaxLength int    `yaml:"max_length"`
					Title     string `yaml:"title"`
					Type      string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"include_consumer_groups"`
			IncludeTopics struct {
				Items struct {
					Example   string `yaml:"example"`
					MaxLength int    `yaml:"max_length"`
					Title     string `yaml:"title"`
					Type      string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"include_topics"`
			KafkaCustomMetrics struct {
				Items struct {
					Example   string `yaml:"example"`
					MaxLength int    `yaml:"max_length"`
					Title     string `yaml:"title"`
					Type      string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"kafka_custom_metrics"`
			MaxJmxMetrics struct {
				Example string `yaml:"example"`
				Maximum int    `yaml:"maximum"`
				Minimum int    `yaml:"minimum"`
				Title   string `yaml:"title"`
				Type    string `yaml:"type"`
			} `yaml:"max_jmx_metrics"`
		} `yaml:"properties"`
		Type string `yaml:"type"`
	} `yaml:"datadog"`
	Datasource struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"datasource"`
	ExternalAwsCloudwatchLogs struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"external_aws_cloudwatch_logs"`
	ExternalAwsCloudwatchMetrics struct {
		Properties struct {
			DroppedMetrics struct {
				Example []struct {
					Field  string `yaml:"field"`
					Metric string `yaml:"metric"`
				} `yaml:"example"`
				Items struct {
					Properties struct {
						Field struct {
							Example   string `yaml:"example"`
							MaxLength int    `yaml:"max_length"`
							Title     string `yaml:"title"`
							Type      string `yaml:"type"`
						} `yaml:"field"`
						Metric struct {
							Example   string `yaml:"example"`
							MaxLength int    `yaml:"max_length"`
							Title     string `yaml:"title"`
							Type      string `yaml:"type"`
						} `yaml:"metric"`
					} `yaml:"properties"`
					Title string `yaml:"title"`
					Type  string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"dropped_metrics"`
			ExtraMetrics struct {
				Example []struct {
					Field  string `yaml:"field"`
					Metric string `yaml:"metric"`
				} `yaml:"example"`
				Items struct {
					Properties struct {
						Field struct {
							Example   string `yaml:"example"`
							MaxLength int    `yaml:"max_length"`
							Title     string `yaml:"title"`
							Type      string `yaml:"type"`
						} `yaml:"field"`
						Metric struct {
							Example   string `yaml:"example"`
							MaxLength int    `yaml:"max_length"`
							Title     string `yaml:"title"`
							Type      string `yaml:"type"`
						} `yaml:"metric"`
					} `yaml:"properties"`
					Title string `yaml:"title"`
					Type  string `yaml:"type"`
				} `yaml:"items"`
				MaxItems int    `yaml:"maxItems"`
				Title    string `yaml:"title"`
				Type     string `yaml:"type"`
			} `yaml:"extra_metrics"`
		} `yaml:"properties"`
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"external_aws_cloudwatch_metrics"`
	ExternalElasticsearchLogs struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"external_elasticsearch_logs"`
	ExternalGoogleCloudLogging struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"external_google_cloud_logging"`
	ExternalOpensearchLogs struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"external_opensearch_logs"`
	Flink struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"flink"`
	Jolokia struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"jolokia"`
	KafkaConnect struct {
		Properties struct {
			KafkaConnect struct {
				Properties struct {
					ConfigStorageTopic struct {
						Example   string `yaml:"example"`
						MaxLength int    `yaml:"max_length"`
						Title     string `yaml:"title"`
						Type      string `yaml:"type"`
					} `yaml:"config_storage_topic"`
					GroupID struct {
						Example   string `yaml:"example"`
						MaxLength int    `yaml:"max_length"`
						Title     string `yaml:"title"`
						Type      string `yaml:"type"`
					} `yaml:"group_id"`
					OffsetStorageTopic struct {
						Example   string `yaml:"example"`
						MaxLength int    `yaml:"max_length"`
						Title     string `yaml:"title"`
						Type      string `yaml:"type"`
					} `yaml:"offset_storage_topic"`
					StatusStorageTopic struct {
						Example   string `yaml:"example"`
						MaxLength int    `yaml:"max_length"`
						Title     string `yaml:"title"`
						Type      string `yaml:"type"`
					} `yaml:"status_storage_topic"`
				} `yaml:"properties"`
				Title string `yaml:"title"`
				Type  string `yaml:"type"`
			} `yaml:"kafka_connect"`
		} `yaml:"properties"`
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"kafka_connect"`
	KafkaLogs struct {
		Properties struct {
			KafkaTopic struct {
				Example   string `yaml:"example"`
				MaxLength int    `yaml:"max_length"`
				MinLength int    `yaml:"min_length"`
				Pattern   string `yaml:"pattern"`
				Title     string `yaml:"title"`
				Type      string `yaml:"type"`
				UserError string `yaml:"user_error"`
			} `yaml:"kafka_topic"`
		} `yaml:"properties"`
		Type string `yaml:"type"`
	} `yaml:"kafka_logs"`
	KafkaMirrormaker struct {
		Properties struct {
			ClusterAlias struct {
				Description string `yaml:"description"`
				Example     string `yaml:"example"`
				MaxLength   int    `yaml:"max_length"`
				Pattern     string `yaml:"pattern"`
				Title       string `yaml:"title"`
				Type        string `yaml:"type"`
				UserError   string `yaml:"user_error"`
			} `yaml:"cluster_alias"`
			KafkaMirrormaker struct {
				Properties struct {
					ConsumerFetchMinBytes struct {
						Description string  `yaml:"description"`
						Example     string  `yaml:"example"`
						Maximum     float64 `yaml:"maximum"`
						Minimum     int     `yaml:"minimum"`
						Title       string  `yaml:"title"`
						Type        string  `yaml:"type"`
					} `yaml:"consumer_fetch_min_bytes"`
					ProducerBatchSize struct {
						Description string  `yaml:"description"`
						Example     string  `yaml:"example"`
						Maximum     float64 `yaml:"maximum"`
						Title       string  `yaml:"title"`
						Type        string  `yaml:"type"`
					} `yaml:"producer_batch_size"`
					ProducerBufferMemory struct {
						Description string  `yaml:"description"`
						Example     string  `yaml:"example"`
						Maximum     float64 `yaml:"maximum"`
						Minimum     float64 `yaml:"minimum"`
						Title       string  `yaml:"title"`
						Type        string  `yaml:"type"`
					} `yaml:"producer_buffer_memory"`
					ProducerLingerMs struct {
						Description string `yaml:"description"`
						Example     string `yaml:"example"`
						Maximum     int    `yaml:"maximum"`
						Title       string `yaml:"title"`
						Type        string `yaml:"type"`
					} `yaml:"producer_linger_ms"`
					ProducerMaxRequestSize struct {
						Description string  `yaml:"description"`
						Example     string  `yaml:"example"`
						Maximum     float64 `yaml:"maximum"`
						Title       string  `yaml:"title"`
						Type        string  `yaml:"type"`
					} `yaml:"producer_max_request_size"`
				} `yaml:"properties"`
				Title string `yaml:"title"`
				Type  string `yaml:"type"`
			} `yaml:"kafka_mirrormaker"`
		} `yaml:"properties"`
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"kafka_mirrormaker"`
	Logs struct {
		Properties struct {
			ElasticsearchIndexDaysMax struct {
				Default string `yaml:"default"`
				Example string `yaml:"example"`
				Maximum int    `yaml:"maximum"`
				Minimum int    `yaml:"minimum"`
				Title   string `yaml:"title"`
				Type    string `yaml:"type"`
			} `yaml:"elasticsearch_index_days_max"`
			ElasticsearchIndexPrefix struct {
				Default   string `yaml:"default"`
				Example   string `yaml:"example"`
				MaxLength int    `yaml:"max_length"`
				MinLength int    `yaml:"min_length"`
				Title     string `yaml:"title"`
				Type      string `yaml:"type"`
			} `yaml:"elasticsearch_index_prefix"`
		} `yaml:"properties"`
		Type string `yaml:"type"`
	} `yaml:"logs"`
	M3aggregator struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"m3aggregator"`
	M3coordinator struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"m3coordinator"`
	Metrics struct {
		Properties struct {
			Database struct {
				Example   string `yaml:"example"`
				MaxLength int    `yaml:"max_length"`
				Pattern   string `yaml:"pattern"`
				Title     string `yaml:"title"`
				Type      string `yaml:"type"`
				UserError string `yaml:"user_error"`
			} `yaml:"database"`
			RetentionDays struct {
				Example string `yaml:"example"`
				Maximum int    `yaml:"maximum"`
				Title   string `yaml:"title"`
				Type    string `yaml:"type"`
			} `yaml:"retention_days"`
			RoUsername struct {
				Example   string `yaml:"example"`
				MaxLength int    `yaml:"max_length"`
				Pattern   string `yaml:"pattern"`
				Title     string `yaml:"title"`
				Type      string `yaml:"type"`
				UserError string `yaml:"user_error"`
			} `yaml:"ro_username"`
			SourceMysql struct {
				Properties struct {
					Telegraf struct {
						Properties struct {
							GatherEventWaits struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_event_waits"`
							GatherFileEventsStats struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_file_events_stats"`
							GatherIndexIoWaits struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_index_io_waits"`
							GatherInfoSchemaAutoInc struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_info_schema_auto_inc"`
							GatherInnodbMetrics struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_innodb_metrics"`
							GatherPerfEventsStatements struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_perf_events_statements"`
							GatherProcessList struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_process_list"`
							GatherSlaveStatus struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_slave_status"`
							GatherTableIoWaits struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_table_io_waits"`
							GatherTableLockWaits struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_table_lock_waits"`
							GatherTableSchema struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_table_schema"`
							PerfEventsStatementsDigestTextLimit struct {
								Example string `yaml:"example"`
								Maximum int    `yaml:"maximum"`
								Minimum int    `yaml:"minimum"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"perf_events_statements_digest_text_limit"`
							PerfEventsStatementsLimit struct {
								Example string `yaml:"example"`
								Maximum int    `yaml:"maximum"`
								Minimum int    `yaml:"minimum"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"perf_events_statements_limit"`
							PerfEventsStatementsTimeLimit struct {
								Example string  `yaml:"example"`
								Maximum float64 `yaml:"maximum"`
								Minimum int     `yaml:"minimum"`
								Title   string  `yaml:"title"`
								Type    string  `yaml:"type"`
							} `yaml:"perf_events_statements_time_limit"`
						} `yaml:"properties"`
						Title string `yaml:"title"`
						Type  string `yaml:"type"`
					} `yaml:"telegraf"`
				} `yaml:"properties"`
				Title string `yaml:"title"`
				Type  string `yaml:"type"`
			} `yaml:"source_mysql"`
			Username struct {
				Example   string `yaml:"example"`
				MaxLength int    `yaml:"max_length"`
				Pattern   string `yaml:"pattern"`
				Title     string `yaml:"title"`
				Type      string `yaml:"type"`
				UserError string `yaml:"user_error"`
			} `yaml:"username"`
		} `yaml:"properties"`
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"metrics"`
	Prometheus struct {
		Properties struct {
			SourceMysql struct {
				Properties struct {
					Telegraf struct {
						Properties struct {
							GatherEventWaits struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_event_waits"`
							GatherFileEventsStats struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_file_events_stats"`
							GatherIndexIoWaits struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_index_io_waits"`
							GatherInfoSchemaAutoInc struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_info_schema_auto_inc"`
							GatherInnodbMetrics struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_innodb_metrics"`
							GatherPerfEventsStatements struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_perf_events_statements"`
							GatherProcessList struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_process_list"`
							GatherSlaveStatus struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_slave_status"`
							GatherTableIoWaits struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_table_io_waits"`
							GatherTableLockWaits struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_table_lock_waits"`
							GatherTableSchema struct {
								Example bool   `yaml:"example"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"gather_table_schema"`
							PerfEventsStatementsDigestTextLimit struct {
								Example string `yaml:"example"`
								Maximum int    `yaml:"maximum"`
								Minimum int    `yaml:"minimum"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"perf_events_statements_digest_text_limit"`
							PerfEventsStatementsLimit struct {
								Example string `yaml:"example"`
								Maximum int    `yaml:"maximum"`
								Minimum int    `yaml:"minimum"`
								Title   string `yaml:"title"`
								Type    string `yaml:"type"`
							} `yaml:"perf_events_statements_limit"`
							PerfEventsStatementsTimeLimit struct {
								Example string  `yaml:"example"`
								Maximum float64 `yaml:"maximum"`
								Minimum int     `yaml:"minimum"`
								Title   string  `yaml:"title"`
								Type    string  `yaml:"type"`
							} `yaml:"perf_events_statements_time_limit"`
						} `yaml:"properties"`
						Title string `yaml:"title"`
						Type  string `yaml:"type"`
					} `yaml:"telegraf"`
				} `yaml:"properties"`
				Title string `yaml:"title"`
				Type  string `yaml:"type"`
			} `yaml:"source_mysql"`
		} `yaml:"properties"`
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"prometheus"`
	Rsyslog struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"rsyslog"`
	Signalfx struct {
		Title string `yaml:"title"`
		Type  string `yaml:"type"`
	} `yaml:"signalfx"`
}
