// Copyright (c) 2025 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package usergroupmember

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/hashicorp/terraform-plugin-framework/diag"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/errmsg"
)

var ResourceOptions = adapter.ResourceOptions[*resourceModel, tfModel]{
	Create:       createView,
	Delete:       deleteView,
	IDFields:     idFields(),
	Read:         readView,
	RefreshState: true,
	Schema:       resourceSchema,
	TypeName:     typeName,
}

func readView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		rsp, err := client.UserGroupMemberList(ctx, state.OrganizationID.ValueString(), state.GroupID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("UserGroupMemberList Error", err))
			return
		}
		for _, v := range rsp {
			if v.UserId == state.UserID.ValueString() {
				diags.Append(flattenData(ctx, state, &v)...)
				return
			}
		}
		diags.AddError("Resource Not Found", "`aiven_organization_user_group_member` with given `user_id` not found")
	}()
	return diags
}
