// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package usergroupmember

import (
	"context"
	"fmt"

	avngen "github.com/aiven/go-client-codegen"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

const typeName = "aiven_organization_user_group_member"

// idFields the ID attribute fields, i.e.:
// terraform import aiven_organization_user_group_member.foo ORGANIZATION_ID/GROUP_ID/USER_ID
func idFields() []string {
	return []string{"organization_id", "group_id", "user_id"}
}

var ResourceOptions = adapter.ResourceOptions{
	Create:         createView,
	Delete:         deleteView,
	IDFields:       idFields(),
	Read:           readView,
	RefreshState:   true,
	Schema:         resourceSchema,
	SchemaInternal: resourceSchemaInternal(),
	TypeName:       typeName,
}

func readView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	rsp, err := client.UserGroupMemberList(ctx, d.Get("organization_id").(string), d.Get("group_id").(string))
	if err != nil {
		return err
	}
	match, err := adapter.FindOne(rsp, func(i int) bool {
		return adapter.Equal(rsp[i].UserId, d.Get("user_id"))
	})
	if err != nil {
		return fmt.Errorf("lookup `aiven_organization_user_group_member` by `user_id`: %w", err)
	}
	return d.Flatten(&match)
}
