// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package servicelist

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

func datasourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID, equal to `project`.",
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project name.",
				Required:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"services": schema.ListNestedBlock{
				MarkdownDescription: "List of services under the project.",
				NestedObject: schema.NestedBlockObject{Attributes: map[string]schema.Attribute{
					"cloud_description": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Cloud provider and location.",
					},
					"cloud_name": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Target cloud.",
					},
					"create_time": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Service creation timestamp (ISO 8601).",
					},
					"disk_space_mb": schema.Int64Attribute{
						Computed:            true,
						MarkdownDescription: "Megabytes of disk space for data storage.",
					},
					"is_cluster_plan": schema.BoolAttribute{
						Computed:            true,
						MarkdownDescription: "True when the service uses a cluster plan with dedicated node groups.",
					},
					"node_count": schema.Int64Attribute{
						Computed:            true,
						MarkdownDescription: "Number of service nodes in the active plan.",
					},
					"node_cpu_count": schema.Int64Attribute{
						Computed:            true,
						MarkdownDescription: "Number of CPUs for each node.",
					},
					"node_memory_mb": schema.Float64Attribute{
						Computed:            true,
						MarkdownDescription: "Megabytes of memory for each node.",
					},
					"plan": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Subscription plan.",
					},
					"project_vpc_id": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Project VPC ID.",
					},
					"service_name": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Service name.",
					},
					"service_type": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Service type code.",
					},
					"service_type_description": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Single line description of the service.",
					},
					"service_uri": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "URI for connecting to the service (may be null).",
						Sensitive:           true,
					},
					"state": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "State of the service. The possible values are `POWEROFF`, `REBALANCING`, `REBUILDING` and `RUNNING`.",
					},
					"termination_protection": schema.BoolAttribute{
						Computed:            true,
						MarkdownDescription: "Service is protected against termination and powering off.",
					},
					"update_time": schema.StringAttribute{
						Computed:            true,
						MarkdownDescription: "Service last update timestamp (ISO 8601).",
					},
				}},
			},
			"timeouts": timeouts.Block(ctx),
		},
		MarkdownDescription: "A list of all services in a project.",
	}
}
func datasourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"project": &adapter.Schema{Type: adapter.SchemaTypeString},
			"services": &adapter.Schema{
				Computed: true,
				Items: &adapter.Schema{
					Computed: true,
					Properties: map[string]*adapter.Schema{
						"cloud_description": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"cloud_name": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"create_time": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"disk_space_mb": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeInt,
						},
						"is_cluster_plan": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeBool,
						},
						"node_count": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeInt,
						},
						"node_cpu_count": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeInt,
						},
						"node_memory_mb": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeFloat,
						},
						"plan": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"project_vpc_id": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"service_name": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"service_type": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"service_type_description": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"service_uri": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"state": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
						"termination_protection": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeBool,
						},
						"update_time": &adapter.Schema{
							Computed: true,
							Type:     adapter.SchemaTypeString,
						},
					},
					Type: adapter.SchemaTypeObject,
				},
				Type: adapter.SchemaTypeList,
			},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{"read": &adapter.Schema{Type: adapter.SchemaTypeString}},
				Type:       adapter.SchemaTypeObject,
			},
		},
		Type: adapter.SchemaTypeObject,
	}
}
