package user

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/aiven/go-client-codegen/handler/service"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/util"
)

func init() {
	ResourceOptions.Create = createView
	ResourceOptions.Update = updateView
}

func createView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	var req service.ServiceUserCreateIn
	err := d.Expand(&req, expandModifier(ctx, client))
	if err != nil {
		return err
	}

	_, err = client.ServiceUserCreate(ctx, d.Get("project").(string), d.Get("service_name").(string), &req)
	if err != nil {
		return err
	}

	return resetPassword(ctx, client, d)
}

func updateView(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	if d.HasChange("pg_allow_replication") {
		req := &service.ServiceUserCredentialsModifyIn{
			Operation: service.ServiceUserCredentialsModifyOperationTypeSetAccessControl,
			AccessControl: &service.AccessControlIn{
				PGAllowReplication: new(d.Get("pg_allow_replication").(bool)),
			},
		}
		_, err := client.ServiceUserCredentialsModify(ctx, d.Get("project").(string), d.Get("service_name").(string), d.Get("username").(string), req)
		if err != nil {
			return err
		}
	}

	return resetPassword(ctx, client, d)
}

// resetPassword resets the password for a service user.
func resetPassword(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	password := util.NilIfZero(d.Get("password").(string), d.Get("password_wo").(string))
	if d.IsNewResource() && password == nil {
		// The resource is being created, but user did not provide a password.
		// The password will be auto-generated by the backend and read during the RefreshState phase.
		return nil
	}

	if !d.HasChange("password") && !d.HasChange("password_wo_version") {
		// The password has not changed, so no need to reset it.
		return nil
	}

	req := &service.ServiceUserCredentialsModifyIn{
		Operation:   service.ServiceUserCredentialsModifyOperationTypeResetCredentials,
		NewPassword: password,
	}

	_, err := client.ServiceUserCredentialsModify(ctx, d.Get("project").(string), d.Get("service_name").(string), d.Get("username").(string), req)
	return err
}

func expandModifier(_ context.Context, _ avngen.Client) adapter.MapModifier {
	return func(d adapter.ResourceData, dto map[string]any) error {
		// Move pg_allow_replication into access_control for the API request
		if v, ok := d.GetOk("pg_allow_replication"); ok {
			dto["access_control"] = map[string]any{"pg_allow_replication": v}
			delete(dto, "pg_allow_replication")
		}
		return nil
	}
}

func flattenModifier(_ context.Context, _ avngen.Client) adapter.MapModifier {
	return func(d adapter.ResourceData, dto map[string]any) error {
		// pg_allow_replication: use plan value if known, otherwise extract from access_control.
		if v, ok := dto["access_control"]; ok {
			dto["pg_allow_replication"] = v.(map[string]any)["pg_allow_replication"]
			delete(dto, "access_control")
		}

		// Clear password from state when using write-only password.
		_, ok := d.Schema().Properties["password_wo_version"]
		if ok && d.Get("password_wo_version").(int) != 0 {
			delete(dto, "password")
		}
		return nil
	}
}
