// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package mirrormakerreplicationflow

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

func datasourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"config_properties_exclude": schema.SetAttribute{
				Computed:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "List of topic configuration properties and/or regexes that should not be replicated. If omitted, MirrorMaker will use default list of exclusions. For stability reasons, we always include the `unclean.leader.election.enable` field in the excluded parameters. If you have specific requirements for this configuration, please reach out to our support team for assistance.",
			},
			"emit_backward_heartbeats_enabled": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Whether to emit heartbeats to the direction opposite to the flow, i.e. to the source cluster. The default value is `false`.",
			},
			"emit_heartbeats_enabled": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Whether to emit heartbeats to the target cluster. The default value is `false`.",
			},
			"enable": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Is replication flow enabled.",
			},
			"exactly_once_delivery_enabled": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Whether to enable exactly-once message delivery. We recommend you set this to enabled for new replications. The default value is `false`.",
			},
			"follower_fetching_enabled": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Assigns a Rack ID based on the availability-zone to enable follower fetching and rack awareness per replication flow.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `project/service_name/source_cluster/target_cluster`.",
			},
			"offset_lag_max": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "How out-of-sync a remote partition can be before it is resynced (default: 100).",
			},
			"offset_syncs_topic_location": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The location of the offset-syncs topic. The possible values are `source` and `target`.",
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project name.",
				Required:            true,
			},
			"replication_factor": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "Replication factor used when creating the remote topics. If the replication factor surpasses the number of nodes in the target cluster, topic creation will fail.",
			},
			"replication_policy_class": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Class which defines the remote topic naming convention. The possible values are `org.apache.kafka.connect.mirror.DefaultReplicationPolicy` and `org.apache.kafka.connect.mirror.IdentityReplicationPolicy`.",
			},
			"service_name": schema.StringAttribute{
				MarkdownDescription: "Service name.",
				Required:            true,
			},
			"source_cluster": schema.StringAttribute{
				MarkdownDescription: "The alias of the source cluster to use in this replication flow. Can contain the following symbols: ASCII alphanumerics, `.`, `_`, and `-`.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(128)},
			},
			"sync_group_offsets_enabled": schema.BoolAttribute{
				Computed:            true,
				MarkdownDescription: "Whether to periodically write the translated offsets of replicated consumer groups (in the source cluster) to __consumer_offsets topic in target cluster, as long as no active consumers in that group are connected to the target cluster. The default value is `false`.",
			},
			"sync_group_offsets_interval_seconds": schema.Int64Attribute{
				Computed:            true,
				MarkdownDescription: "Frequency at which consumer group offsets are synced (default: 60, every minute). The default value is `1`.",
			},
			"target_cluster": schema.StringAttribute{
				MarkdownDescription: "The alias of the target cluster to use in this replication flow. Can contain the following symbols: ASCII alphanumerics, `.`, `_`, and `-`.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(128)},
			},
			"topics": schema.ListAttribute{
				Computed:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "Topic names and regular expressions that match topic names that should be replicated. MirrorMaker will replicate these topics if they are not matched by `topics_blacklist`. The topics to include are defined by a [list of regular expressions in Java format](https://aiven.io/docs/products/kafka/kafka-mirrormaker/concepts/replication-flow-topics-regex).",
			},
			"topics_blacklist": schema.ListAttribute{
				Computed:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "Topic names and regular expressions that match topic names that should not be replicated. MirrorMaker will not replicate these topics even if they are matched by `topics`. The topics to exclude are defined by a [list of regular expressions in Java format](https://aiven.io/docs/products/kafka/kafka-mirrormaker/concepts/replication-flow-topics-regex).",
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": timeouts.Block(ctx)},
		MarkdownDescription: "Gets information about an [Aiven for Apache Kafka® MirrorMaker 2](https://aiven.io/docs/products/kafka/kafka-mirrormaker) replication flow.",
	}
}
func datasourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"config_properties_exclude": &adapter.Schema{
				Computed: true,
				Items: &adapter.Schema{
					Computed: true,
					Type:     adapter.SchemaTypeString,
				},
				Type: adapter.SchemaTypeSet,
			},
			"emit_backward_heartbeats_enabled": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeBool,
			},
			"emit_heartbeats_enabled": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeBool,
			},
			"enable": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeBool,
			},
			"exactly_once_delivery_enabled": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeBool,
			},
			"follower_fetching_enabled": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeBool,
			},
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"offset_lag_max": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeInt,
			},
			"offset_syncs_topic_location": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"project": &adapter.Schema{Type: adapter.SchemaTypeString},
			"replication_factor": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeInt,
			},
			"replication_policy_class": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"service_name":   &adapter.Schema{Type: adapter.SchemaTypeString},
			"source_cluster": &adapter.Schema{Type: adapter.SchemaTypeString},
			"sync_group_offsets_enabled": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeBool,
			},
			"sync_group_offsets_interval_seconds": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeInt,
			},
			"target_cluster": &adapter.Schema{Type: adapter.SchemaTypeString},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{"read": &adapter.Schema{Type: adapter.SchemaTypeString}},
				Type:       adapter.SchemaTypeObject,
			},
			"topics": &adapter.Schema{
				Computed: true,
				Items: &adapter.Schema{
					Computed: true,
					Type:     adapter.SchemaTypeString,
				},
				Type: adapter.SchemaTypeList,
			},
			"topics_blacklist": &adapter.Schema{
				Computed: true,
				Items: &adapter.Schema{
					Computed: true,
					Type:     adapter.SchemaTypeString,
				},
				Type: adapter.SchemaTypeList,
			},
		},
		Type: adapter.SchemaTypeObject,
	}
}
