// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package database

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/legacytimeouts"
)

/*
resourceSchema:

	resource "aiven_clickhouse_database" "example" {
	  project                = "foo" // Force new
	  service_name           = "test" // Force new
	  name                   = "testdb" // Force new
	  termination_protection = false // Deprecated
	}
*/
func resourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `project/service_name/name`.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Service database name. Maximum length: `40`. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(40)},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"service_name": schema.StringAttribute{
				MarkdownDescription: "Service name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"termination_protection": schema.BoolAttribute{
				Computed:            true,
				Default:             booldefault.StaticBool(false),
				DeprecationMessage:  "Instead, use [`prevent_destroy`](https://developer.hashicorp.com/terraform/tutorials/state/resource-lifecycle#prevent-resource-deletion)",
				MarkdownDescription: "Client-side deletion protection that prevents the resource from being deleted by Terraform. **Resource can still be deleted in the Aiven Console**. The default value is `false`. **Deprecated**: Instead, use [`prevent_destroy`](https://developer.hashicorp.com/terraform/tutorials/state/resource-lifecycle#prevent-resource-deletion)",
				Optional:            true,
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": legacytimeouts.BlockAll(ctx)},
		MarkdownDescription: "Creates and manages an [Aiven for ClickHouse](https://aiven.io/docs/products/clickhouse) database. If this resource is missing (for example, after a service power off), it's removed from the state and a new create plan is generated.",
	}
}
func resourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"name":         &adapter.Schema{Type: adapter.SchemaTypeString},
			"project":      &adapter.Schema{Type: adapter.SchemaTypeString},
			"service_name": &adapter.Schema{Type: adapter.SchemaTypeString},
			"termination_protection": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeBool,
			},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{
					"create":  &adapter.Schema{Type: adapter.SchemaTypeString},
					"default": &adapter.Schema{Type: adapter.SchemaTypeString},
					"delete":  &adapter.Schema{Type: adapter.SchemaTypeString},
					"read":    &adapter.Schema{Type: adapter.SchemaTypeString},
					"update":  &adapter.Schema{Type: adapter.SchemaTypeString},
				},
				Type: adapter.SchemaTypeObject,
			},
		},
		Type: adapter.SchemaTypeObject,
	}
}
