// Copyright (c) 2025 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package userlist

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// datasourceModel with specific datasource timeouts
type datasourceModel struct {
	tfModel
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

func (tf *datasourceModel) SharedModel() *tfModel {
	return &tf.tfModel
}

func (tf *datasourceModel) TimeoutsObject() types.Object {
	return tf.Timeouts.Object
}

/*
datasourceSchema:

	data "aiven_organization_user_list" "example" {
	  id = "foo"

	  // COMPUTED FIELDS
	  name = "test"
	  users {
	    is_super_admin     = true
	    join_time          = "foo"
	    last_activity_time = "foo"
	    user_id            = "foo"
	    user_info {
	      city                     = "foo"
	      country                  = "foo"
	      create_time              = "foo"
	      department               = "foo"
	      is_application_user      = true
	      job_title                = "foo"
	      managed_by_scim          = true
	      managing_organization_id = "org1a23f456789"
	      real_name                = "test"
	      state                    = "foo"
	      user_email               = "test@example.com"
	    }
	  }
	}
*/
func datasourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "ID of an organization. Exactly one of the fields must be specified: `id` or `name`.",
				Optional:            true,
			},
			"name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The name of the organization. Exactly one of the fields must be specified: `id` or `name`.",
				Optional:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx),
			"users": schema.ListNestedBlock{
				MarkdownDescription: "List of users of the organization.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"is_super_admin": schema.BoolAttribute{
							Computed:            true,
							MarkdownDescription: "Super admin state of the organization user.",
						},
						"join_time": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Join time.",
						},
						"last_activity_time": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "Last activity time.",
						},
						"user_id": schema.StringAttribute{
							Computed:            true,
							MarkdownDescription: "User ID.",
						},
					},
					Blocks: map[string]schema.Block{"user_info": schema.ListNestedBlock{
						MarkdownDescription: "OrganizationUserInfo.",
						NestedObject: schema.NestedBlockObject{Attributes: map[string]schema.Attribute{
							"city": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "City.",
							},
							"country": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "Country.",
							},
							"create_time": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "Creation time.",
							},
							"department": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "Department.",
							},
							"is_application_user": schema.BoolAttribute{
								Computed:            true,
								MarkdownDescription: "Is Application User.",
							},
							"job_title": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "Job Title.",
							},
							"managed_by_scim": schema.BoolAttribute{
								Computed:            true,
								MarkdownDescription: "Managed By Scim.",
							},
							"managing_organization_id": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "Managing Organization ID.",
							},
							"real_name": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "Real Name.",
							},
							"state": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "State.",
							},
							"user_email": schema.StringAttribute{
								Computed:            true,
								MarkdownDescription: "User Email.",
							},
						}},
					}},
				},
			},
		},
		MarkdownDescription: "Returns a list of [users in the organization](https://aiven.io/docs/platform/concepts/user-access-management), their profile details, and other data . This includes users you add to your organization and application users.",
	}
}
