#!/bin/sh

TYPE=$1
FILE_NAME=$2
BASEDIR=$(dirname "$0")
JSON=$(cat "$BASEDIR"/"$FILE_NAME")

cat >"$BASEDIR"/"${TYPE}"_user_config_schema.go <<EOL
// Code generated by go generate; DO NOT EDIT.
// This file was generated at $(date)

package templates

import "encoding/json"

var (
  // inline JSON was taken from a file:
  // ${FILE_NAME}
  ${TYPE}JSON = \`${JSON}\`
)

func init() {
  var ${TYPE}Schema map[string]interface{}
  if err := json.Unmarshal([]byte(${TYPE}JSON), &${TYPE}Schema); err != nil {
    panic("cannot unmarshal user configuration options ${TYPE} JSON', error :" + err.Error())
  }
  userConfigSchemas["${TYPE}"] = ${TYPE}Schema
}
EOL
