// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package usergroupmemberlist

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/util"
)

const typeName = "aiven_organization_user_group_member_list"

type tfModel struct {
	ID             types.String `tfsdk:"id"`
	Members        types.Set    `tfsdk:"members"`
	OrganizationID types.String `tfsdk:"organization_id"`
	UserGroupID    types.String `tfsdk:"user_group_id"`
}

func (tf *tfModel) SetID(vOrganizationID string, vUserGroupID string) {
	tf.OrganizationID = types.StringValue(vOrganizationID)
	tf.UserGroupID = types.StringValue(vUserGroupID)
	tf.ID = types.StringValue(filepath.Join(vOrganizationID, vUserGroupID))
}

type tfModelMembers struct {
	LastActivityTime types.String `tfsdk:"last_activity_time"`
	UserID           types.String `tfsdk:"user_id"`
	UserInfo         types.List   `tfsdk:"user_info"`
}

type tfModelMembersUserInfo struct {
	City                   types.String `tfsdk:"city"`
	Country                types.String `tfsdk:"country"`
	CreateTime             types.String `tfsdk:"create_time"`
	Department             types.String `tfsdk:"department"`
	IsApplicationUser      types.Bool   `tfsdk:"is_application_user"`
	JobTitle               types.String `tfsdk:"job_title"`
	ManagedByScim          types.Bool   `tfsdk:"managed_by_scim"`
	ManagingOrganizationID types.String `tfsdk:"managing_organization_id"`
	RealName               types.String `tfsdk:"real_name"`
	State                  types.String `tfsdk:"state"`
	UserEmail              types.String `tfsdk:"user_email"`
}

type apiModel struct {
	Members        *[]*apiModelMembers `json:"members,omitempty"`
	OrganizationID *string             `json:"organization_id,omitempty"`
	UserGroupID    *string             `json:"user_group_id,omitempty"`
}

type apiModelMembers struct {
	LastActivityTime *string                  `json:"last_activity_time,omitempty"`
	UserID           *string                  `json:"user_id,omitempty"`
	UserInfo         *apiModelMembersUserInfo `json:"user_info,omitempty"`
}

type apiModelMembersUserInfo struct {
	City                   *string `json:"city,omitempty"`
	Country                *string `json:"country,omitempty"`
	CreateTime             *string `json:"create_time,omitempty"`
	Department             *string `json:"department,omitempty"`
	IsApplicationUser      *bool   `json:"is_application_user,omitempty"`
	JobTitle               *string `json:"job_title,omitempty"`
	ManagedByScim          *bool   `json:"managed_by_scim,omitempty"`
	ManagingOrganizationID *string `json:"managing_organization_id,omitempty"`
	RealName               *string `json:"real_name,omitempty"`
	State                  *string `json:"state,omitempty"`
	UserEmail              *string `json:"user_email,omitempty"`
}

// flattenData turns Response into TF object
func flattenData[R any](ctx context.Context, state *tfModel, rsp *R, modifiers ...util.MapModifier[tfModel]) diag.Diagnostics {
	api := new(apiModel)
	err := util.Remarshal(rsp, api, state, modifiers...)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("Remarshal error", fmt.Sprintf("Failed to remarshal Response to dtoModel: %s", err.Error()))
		return diags
	}
	if api.Members != nil {
		vMembers, diags := util.FlattenSetNested(ctx, flattenMembers, *api.Members, attrsMembers())
		if diags.HasError() {
			return diags
		}
		state.Members = vMembers
	}
	if api.OrganizationID != nil && !state.OrganizationID.IsUnknown() {
		state.OrganizationID = util.StringPointerValue(api.OrganizationID)
	}
	if api.UserGroupID != nil && !state.UserGroupID.IsUnknown() {
		state.UserGroupID = util.StringPointerValue(api.UserGroupID)
	}
	// Response may not contain ID fields.
	// In that case, `terraform import` won't be able to set them. Gets values from the ID.
	if state.ID.ValueString() != "" {
		var parts [2]string
		for i, v := range strings.SplitN(state.ID.ValueString(), "/", 2) {
			parts[i] = v
		}
		if state.OrganizationID.ValueString() == "" {
			state.OrganizationID = types.StringValue(parts[0])
		}
		if state.UserGroupID.ValueString() == "" {
			state.UserGroupID = types.StringValue(parts[1])
		}
	}
	state.SetID(state.OrganizationID.ValueString(), state.UserGroupID.ValueString())
	return nil
}

func flattenMembers(ctx context.Context, api *apiModelMembers) (*tfModelMembers, diag.Diagnostics) {
	state := new(tfModelMembers)
	if api.UserInfo != nil {
		vUserInfo, diags := util.FlattenSingleNested(ctx, flattenMembersUserInfo, api.UserInfo, attrsMembersUserInfo())
		if diags.HasError() {
			return nil, diags
		}
		state.UserInfo = vUserInfo
	}
	if api.LastActivityTime != nil {
		state.LastActivityTime = util.StringPointerValue(api.LastActivityTime)
	}
	if api.UserID != nil {
		state.UserID = util.StringPointerValue(api.UserID)
	}
	return state, nil
}

func flattenMembersUserInfo(ctx context.Context, api *apiModelMembersUserInfo) (*tfModelMembersUserInfo, diag.Diagnostics) {
	state := new(tfModelMembersUserInfo)
	if api.City != nil {
		state.City = util.StringPointerValue(api.City)
	}
	if api.Country != nil {
		state.Country = util.StringPointerValue(api.Country)
	}
	if api.CreateTime != nil {
		state.CreateTime = util.StringPointerValue(api.CreateTime)
	}
	if api.Department != nil {
		state.Department = util.StringPointerValue(api.Department)
	}
	if api.IsApplicationUser != nil {
		state.IsApplicationUser = types.BoolPointerValue(api.IsApplicationUser)
	}
	if api.JobTitle != nil {
		state.JobTitle = util.StringPointerValue(api.JobTitle)
	}
	if api.ManagedByScim != nil {
		state.ManagedByScim = types.BoolPointerValue(api.ManagedByScim)
	}
	if api.ManagingOrganizationID != nil {
		state.ManagingOrganizationID = util.StringPointerValue(api.ManagingOrganizationID)
	}
	if api.RealName != nil {
		state.RealName = util.StringPointerValue(api.RealName)
	}
	if api.State != nil {
		state.State = util.StringPointerValue(api.State)
	}
	if api.UserEmail != nil {
		state.UserEmail = util.StringPointerValue(api.UserEmail)
	}
	return state, nil
}

func attrsMembers() types.ObjectType {
	return types.ObjectType{AttrTypes: map[string]attr.Type{
		"last_activity_time": types.StringType,
		"user_id":            types.StringType,
		"user_info":          types.ListType{ElemType: attrsMembersUserInfo()},
	}}
}

func attrsMembersUserInfo() types.ObjectType {
	return types.ObjectType{AttrTypes: map[string]attr.Type{
		"city":                     types.StringType,
		"country":                  types.StringType,
		"create_time":              types.StringType,
		"department":               types.StringType,
		"is_application_user":      types.BoolType,
		"job_title":                types.StringType,
		"managed_by_scim":          types.BoolType,
		"managing_organization_id": types.StringType,
		"real_name":                types.StringType,
		"state":                    types.StringType,
		"user_email":               types.StringType,
	}}
}
