// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package paymentmethodlist

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/util"
)

const typeName = "aiven_organization_payment_method_list"

type tfModel struct {
	ID             types.String `tfsdk:"id"`
	OrganizationID types.String `tfsdk:"organization_id"`
	PaymentMethods types.Set    `tfsdk:"payment_methods"`
}

func (tf *tfModel) SetID(vOrganizationID string) {
	tf.OrganizationID = types.StringValue(vOrganizationID)
	tf.ID = types.StringValue(filepath.Join(vOrganizationID))
}

type tfModelPaymentMethods struct {
	PaymentMethodID   types.String `tfsdk:"payment_method_id"`
	PaymentMethodType types.String `tfsdk:"payment_method_type"`
}

type apiModel struct {
	OrganizationID *string                    `json:"organization_id,omitempty"`
	PaymentMethods *[]*apiModelPaymentMethods `json:"payment_methods,omitempty"`
}

type apiModelPaymentMethods struct {
	PaymentMethodID   *string `json:"payment_method_id,omitempty"`
	PaymentMethodType *string `json:"payment_method_type,omitempty"`
}

// flattenData turns Response into TF object
func flattenData[R any](ctx context.Context, state *tfModel, rsp *R, modifiers ...util.MapModifier[tfModel]) diag.Diagnostics {
	api := new(apiModel)
	err := util.Remarshal(rsp, api, state, modifiers...)
	if err != nil {
		var diags diag.Diagnostics
		diags.AddError("Remarshal error", fmt.Sprintf("Failed to remarshal Response to dtoModel: %s", err.Error()))
		return diags
	}
	if api.PaymentMethods != nil || state.PaymentMethods.IsUnknown() || state.PaymentMethods.IsNull() {
		vPaymentMethods, diags := util.FlattenSetNested(ctx, flattenPaymentMethods, api.PaymentMethods, attrsPaymentMethods())
		if diags.HasError() {
			return diags
		}
		state.PaymentMethods = vPaymentMethods
	}
	if api.OrganizationID != nil && !state.OrganizationID.IsUnknown() {
		state.OrganizationID = util.StringPointerValue(api.OrganizationID)
	}
	// Response may not contain ID fields.
	// In that case, `terraform import` won't be able to set them. Gets values from the ID.
	if state.ID.ValueString() != "" {
		var parts [1]string
		for i, v := range strings.SplitN(state.ID.ValueString(), "/", 1) {
			parts[i] = v
		}
		if state.OrganizationID.ValueString() == "" {
			state.OrganizationID = types.StringValue(parts[0])
		}
	}
	state.SetID(state.OrganizationID.ValueString())
	return nil
}

func flattenPaymentMethods(ctx context.Context, api *apiModelPaymentMethods) (*tfModelPaymentMethods, diag.Diagnostics) {
	state := new(tfModelPaymentMethods)
	if api.PaymentMethodID != nil || state.PaymentMethodID.IsUnknown() {
		state.PaymentMethodID = util.StringPointerValue(api.PaymentMethodID)
	}
	if api.PaymentMethodType != nil || state.PaymentMethodType.IsUnknown() {
		state.PaymentMethodType = util.StringPointerValue(api.PaymentMethodType)
	}
	return state, nil
}

func attrsPaymentMethods() types.ObjectType {
	return types.ObjectType{AttrTypes: map[string]attr.Type{
		"payment_method_id":   types.StringType,
		"payment_method_type": types.StringType,
	}}
}
