// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package organizationvpc

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

func datasourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cloud_name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "The cloud provider and region where the service is hosted in the format `CLOUD_PROVIDER-REGION_NAME`. For example, `google-europe-west1` or `aws-us-east-2`.",
			},
			"create_time": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "VPC creation timestamp.",
			},
			"display_name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "User defined display name for this VPC.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `organization_id/organization_vpc_id`.",
			},
			"network_cidr": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Network address range used by the VPC. For example, `192.168.0.0/24`.",
			},
			"organization_id": schema.StringAttribute{
				MarkdownDescription: "ID of an organization.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(36)},
			},
			"organization_vpc_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the Aiven Organization VPC.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthBetween(36, 36)},
			},
			"state": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "State of the VPC. The possible values are `ACTIVE`, `APPROVED`, `DELETED` and `DELETING`.",
			},
			"update_time": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Timestamp of last change to VPC.",
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": timeouts.Block(ctx)},
		MarkdownDescription: "Gets information about an existing VPC in an Aiven organization.",
	}
}
func datasourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"cloud_name": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"create_time": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"display_name": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"network_cidr": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"organization_id":     &adapter.Schema{Type: adapter.SchemaTypeString},
			"organization_vpc_id": &adapter.Schema{Type: adapter.SchemaTypeString},
			"state": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{"read": &adapter.Schema{Type: adapter.SchemaTypeString}},
				Type:       adapter.SchemaTypeObject,
			},
			"update_time": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
		},
		Type: adapter.SchemaTypeObject,
	}
}
