// Package serviceuser holds logic shared by the Aiven service user resources
// (aiven_kafka_user, aiven_pg_user, aiven_mysql_user, aiven_opensearch_user).
//
// All of them are backed by the same generic service-user API
// (ServiceUserCreate/Get/Delete + ServiceUserCredentialsModify), so the create
// flow and password/credentials handling are identical. Resource-specific
// extras (e.g. pg_allow_replication, authentication) are layered on top by the
// individual packages.
package serviceuser

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/aiven/go-client-codegen/handler/service"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/util"
)

// CreateUser expands the plan into a ServiceUserCreateIn (applying the given
// expand modifiers, if any) and creates the user. It does not touch the
// password, so resources with a non-default credentials flow (e.g.
// aiven_mysql_user, which also sets authentication) can chain their own reset.
func CreateUser(ctx context.Context, client avngen.Client, d adapter.ResourceData, expandMods ...adapter.MapModifier) error {
	var req service.ServiceUserCreateIn
	if err := d.Expand(&req, expandMods...); err != nil {
		return err
	}

	_, err := client.ServiceUserCreate(ctx, d.Get("project").(string), d.Get("service_name").(string), &req)
	return err
}

// Create runs CreateUser and then the default (no-auth) ResetPassword. It backs
// the create view of resources whose credentials flow is fully standard
// (aiven_kafka_user, aiven_pg_user, aiven_opensearch_user).
func Create(ctx context.Context, client avngen.Client, d adapter.ResourceData, expandMods ...adapter.MapModifier) error {
	if err := CreateUser(ctx, client, d, expandMods...); err != nil {
		return err
	}

	return ResetPassword(ctx, client, d)
}

// ResetPassword resets a service user's password via a credentials reset.
// A nil NewPassword tells the backend to auto-generate one.
//
// Resources that also manage authentication (e.g. aiven_mysql_user) implement
// their own reset that additionally sets the Authentication field.
func ResetPassword(ctx context.Context, client avngen.Client, d adapter.ResourceData) error {
	password := util.NilIfZero(d.Get("password").(string), d.Get("password_wo").(string))
	if d.IsNewResource() && password == nil {
		// The resource is being created, but user did not provide a password.
		// The password will be auto-generated by the backend and read during the RefreshState phase.
		return nil
	}

	if !d.HasChange("password") && !d.HasChange("password_wo_version") {
		// The password has not changed, so no need to reset it.
		return nil
	}

	req := &service.ServiceUserCredentialsModifyIn{
		Operation:   service.ServiceUserCredentialsModifyOperationTypeResetCredentials,
		NewPassword: password,
	}

	_, err := client.ServiceUserCredentialsModify(ctx, d.Get("project").(string), d.Get("service_name").(string), d.Get("username").(string), req)
	return err
}

// PasswordFlatten is a MapModifier that reconciles the password in the API
// response with the plan before it is written to state:
//
//   - It keeps the planned password when known. Password updates on the Aiven
//     API are async, so a freshly read response may still carry an empty
//     password until the change is fully propagated.
//   - It clears the password from state when a write-only password is in use
//     (password_wo_version set), so the secret is never persisted.
func PasswordFlatten(d adapter.ResourceData, dto map[string]any) error {
	if v := d.Get("password").(string); v != "" {
		dto["password"] = v
	}

	if _, ok := d.Schema().Properties["password_wo_version"]; ok && d.Get("password_wo_version").(int) != 0 {
		delete(dto, "password")
	}

	return nil
}
