name: Acceptance Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main

permissions:
  contents: read
  statuses: write
  pull-requests: read
  actions: read

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  gatekeeper:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
      ref_to_test: ${{ steps.check.outputs.ref_to_test }}
    steps:
      - id: check
        name: Check if tests should run
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            echo "Scheduled run. Testing main branch."
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "ref_to_test=refs/heads/main" >> $GITHUB_OUTPUT

          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Manual run from UI. Testing the triggered commit."
            echo "should_run=true" >> $GITHUB_OUTPUT
            echo "ref_to_test=${{ github.sha }}" >> $GITHUB_OUTPUT

          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            if ${{ contains(github.event.pull_request.labels.*.name, 'release') }}; then
              echo "Pull request has 'release' label. Testing PR commit."
              echo "should_run=true" >> $GITHUB_OUTPUT
              echo "ref_to_test=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
            else
              echo "Pull request does not have 'release' label. Skipping."
              echo "should_run=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "Event not configured to run tests. Skipping."
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  call-tests:
    needs: [gatekeeper]
    if: needs.gatekeeper.outputs.should_run == 'true'
    uses: ./.github/workflows/reusable-acceptance-tests.yml
    with:
      ref: ${{ needs.gatekeeper.outputs.ref_to_test }}
    secrets: inherit

  notify-slack-success:
    needs: [call-tests, gatekeeper]
    if: success() && needs.gatekeeper.outputs.should_run == 'true'
    uses: ./.github/workflows/slack-notify.yml
    with:
      status: 'success'
      workflow_name: 'Acceptance Tests'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

  notify-slack-failure:
    needs: [call-tests, gatekeeper]
    if: failure() && needs.gatekeeper.outputs.should_run == 'true'
    uses: ./.github/workflows/slack-notify.yml
    with:
      status: 'failure'
      workflow_name: 'Acceptance Tests'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
