# Workflow performs a security scan on dependency changes within a pull request
# for known vulnerabilities in added or updated modules.
name: Dependency Review

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_call:
    inputs:
      head_ref:
        description: 'The git ref to run checks against (head)'
        required: true
        type: string
      base_ref:
        description: 'The git ref to compare against (base)'
        required: true
        type: string

# TODO: This is currently not supported, see https://github.com/actions/dependency-review-action/issues/30.
#  push:
#    branches:
#      - main

permissions:
  contents: read

jobs:
  gatekeeper:
    uses: ./.github/workflows/reusable-gatekeeper.yml

  dependency-review:
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head_ref || github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ inputs.base_ref || github.event.pull_request.base.ref }}
          head-ref: ${{ inputs.head_ref || github.event.pull_request.head.ref }}
