name: Dependency Review

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  workflow_call:
    inputs:
      ref:
        description: 'The git ref to run checks against'
        required: true
        type: string

# TODO: This is currently not supported, see https://github.com/actions/dependency-review-action/issues/30.
#  push:
#    branches:
#      - main

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip workflows')) || github.event_name == 'push' || github.event_name == 'workflow_call'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/dependency-review-action@v4
