# Workflow runs various linting and static analysis checks, including commit message format,
# Semgrep security scans, Go linting, and documentation generation verification. It runs on
# pull requests to ensure code quality and consistency.
name: Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_call:
    inputs:
      ref:
        description: 'The git ref to run checks against'
        required: true
        type: string

permissions:
  contents: read

jobs:
  gatekeeper:
    uses: ./.github/workflows/reusable-gatekeeper.yml

  commitlint:
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || inputs.ref }}
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6

  semgrep:
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || inputs.ref }}
          fetch-depth: 0
      - run: semgrep --config "p/auto" --config ".semgrep.yml" --include="**" --error

  make_lint:
    runs-on: ubuntu-latest
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: task lint

  check_docs_were_generated:
    runs-on: ubuntu-latest
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: arduino/setup-task@v2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: task ci:docs
      - run: git diff --exit-code --ignore-all-space --ignore-space-change --ignore-blank-lines

  sweep_check:
    runs-on: ubuntu-latest
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
    - uses: arduino/setup-task@v2
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - run: task ci:sweep-check
