name: Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  push:
    branches:
      - main
  workflow_call:
    inputs:
      ref:
        description: 'The git ref to run checks against'
        required: true
        type: string

permissions:
  contents: read

jobs:
  # This job's only purpose is to decide if the next job should run.
  # The output `should_run` will be simple 'true' or 'false'.
  gatekeeper:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Determine if tests should run based on trigger and labels
        id: check
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # Check if the 'skip workflows' label is present on the PR.
            if ${{ contains(github.event.pull_request.labels.*.name, 'skip workflows') }}; then
              echo "INFO: Pull request has 'skip workflows' label"
              echo "should_run=false" >> $GITHUB_OUTPUT
            else
              echo "INFO: Pull request is valid"
              echo "should_run=true" >> $GITHUB_OUTPUT
            fi
          else
            # For all other events like 'workflow_call' or 'push', always run.
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  commitlint:
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || inputs.ref }}
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6

  semgrep:
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || inputs.ref }}
          fetch-depth: 0
      - run: semgrep --config "p/auto" --config ".semgrep.yml" --include="**" --error

  make_lint:
    runs-on: ubuntu-latest
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: task lint

  check_docs_were_generated:
    runs-on: ubuntu-latest
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: arduino/setup-task@v2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: task ci:docs
      - run: git diff --exit-code --ignore-all-space --ignore-space-change --ignore-blank-lines

  sweep_check:
    runs-on: ubuntu-latest
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: arduino/setup-task@v2
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - run: task ci:sweep-check
