name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 4.10.0)'
        required: true
        type: string
      run_acceptance_tests:
        description: 'Run the acceptance tests? (Uncheck to skip, only if you are sure)'
        required: true
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ inputs.version }}
  cancel-in-progress: true

jobs:
  create_release_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    outputs:
      pr_head_sha: ${{ steps.create-pr.outputs.pull-request-head-sha }}
      pr_created: ${{ steps.create-pr.outputs.pull-request-number != '' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify release version
        run: task ci:verify-version VERSION=${{ inputs.version }}

      - name: Setup release branch
        run: |
          BRANCH_NAME="release-v${{ inputs.version }}"
          echo "RELEASE_BRANCH=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Update CHANGELOG.md
        run: |
          task ci:changelog-update VERSION="${{ inputs.version }}"

      - name: Extract changelog content for PR
        id: changelog
        run: |
          CHANGELOG_CONTENT=$(task -s ci:changelog-extract VERSION="${{ inputs.version }}")

          # Store in GitHub env for PR body
          echo "CHANGELOG_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG_CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "chore(release): v${{ inputs.version }}"

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          author: GitHub <noreply@github.com>
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.RELEASE_BRANCH }}
          base: main
          title: "chore(release): v${{ inputs.version }}"
          body: |
            ## Release v${{ inputs.version }}

            ### Changelog
            ${{ env.CHANGELOG_CONTENT }}

            ---

            *This PR was created automatically by the release preparation workflow.*
          labels: |
            release
          draft: false

  # Run all linting-related checks
  run_lint_checks:
    needs: create_release_pr
    if: needs.create_release_pr.outputs.pr_created
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ needs.create_release_pr.outputs.pr_head_sha }}

  # Run unit tests
  run_unit_tests:
    needs: create_release_pr
    if: needs.create_release_pr.outputs.pr_created
    uses: ./.github/workflows/unit-tests.yml
    with:
      ref: ${{ needs.create_release_pr.outputs.pr_head_sha }}

  # Run dependency review
  run_dependency_review:
    needs: create_release_pr
    if: needs.create_release_pr.outputs.pr_created
    uses: ./.github/workflows/dependency-review.yml
    with:
      head_ref: ${{ needs.create_release_pr.outputs.pr_head_sha }}
      base_ref: main

  # Run acceptance tests
  run_acceptance_tests:
    needs: create_release_pr
    if: needs.create_release_pr.outputs.pr_created && inputs.run_acceptance_tests
    uses: ./.github/workflows/reusable-acceptance-tests.yml
    with:
      ref: ${{ needs.create_release_pr.outputs.pr_head_sha }}
    secrets: inherit


  report_all_statuses:
    needs:
      - create_release_pr
      - run_lint_checks
      - run_unit_tests
      - run_dependency_review
      - run_acceptance_tests
    runs-on: ubuntu-latest
    if: always() && needs.create_release_pr.outputs.pr_created == 'true'
    permissions:
      statuses: write
    steps:
      - name: Report status of all required checks
        uses: actions/github-script@v7
        with:
          script: |
            const head_sha = '${{ needs.create_release_pr.outputs.pr_head_sha }}';
            if (!head_sha) {
              console.log('Could not find PR head SHA. Skipping status reporting.');
              return;
            }

            async function postStatus(checkName, result, default_description) {
              let state = 'failure';
              let description = default_description;

              if (result === 'success') {
                state = 'success';
                description = `${checkName} passed`;
              } else if (result === 'skipped') {
                state = 'success';
                description = `${checkName} was skipped`;
              }

              console.log(`Reporting status for context: ${checkName}, state: ${state}`);
              await github.rest.repos.createCommitStatus({
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: head_sha,
                state: state,
                context: checkName,
                description: description,
                target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
              });
            }

            const lintResult = '${{ needs.run_lint_checks.result }}';
            for (const check of ['commitlint', 'semgrep', 'make_lint', 'check_docs_were_generated']) {
              await postStatus(check, lintResult, 'Linting checks failed');
            }

            await postStatus('go_test', '${{ needs.run_unit_tests.result }}', 'Unit tests failed');
            await postStatus('dependency-review', '${{ needs.run_dependency_review.result }}', 'Dependency review failed');
            await postStatus('Acceptance Tests', '${{ needs.run_acceptance_tests.result }}', 'Acceptance tests failed');

            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: head_sha,
              state: 'success',
              context: 'changelog-enforcer',
              description: 'Changelog updated by automated release process.',
              target_url: `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`
            });
