name: Publish Release

on:
  pull_request:
    types:
      - closed
    branches:
      - 'test-target'

jobs:
  tag-and-publish:
    # This job only runs for merged pull requests whose branches start with the release prefix.
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.head_ref, 'release-v')
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permission to create and push a tag

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Extract version from branch name
        id: get_version
        run: |
          # Extracts "vX.Y.Z" from "prefix-release-vX.Y.Z"
          BRANCH_NAME="${{ github.event.pull_request.head_ref }}"
          VERSION=$(echo "$BRANCH_NAME" | sed -n 's/.*-\(v[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1/p')
          if [ -z "$VERSION" ]; then
            echo "Error: Could not extract version from branch '$BRANCH_NAME'"
            exit 1
          fi
          echo "tag=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Create and push tag
        run: |
          echo "Creating and pushing tag ${{ steps.get_version.outputs.tag }}"
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git tag ${{ steps.get_version.outputs.tag }}
          git push origin ${{ steps.get_version.outputs.tag }}
