# This job serves as the manual release fallback process. It is triggered
# whenever a developer manually pushes a new git tag directly to the repository.
#
# This workflow's responsibility is to build artifacts and create a draft release.
# The changelog notes must be added manually as the final step of this process.
name: Manual Artifacts Release

on:
 push:
    tags:
      - 'v*'

jobs:
  build_and_upload_artifacts:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Setup Task
      uses: arduino/setup-task@v2
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - uses: crazy-max/ghaction-import-gpg@v6
      id: import_gpg
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}

    - uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --clean
      env:
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
