name: Sweep

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  sweep:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        aiven_project_name_suffix: [
          '',
          '-2',
          '-3',
          '-4',
          '-5',
        ]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: arduino/setup-task@v2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nick-invision/retry@v3
        if: always()
        with:
          timeout_minutes: 15
          max_attempts: 15
          command: task --yes sweep
        env:
          AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
          AIVEN_PROJECT_NAME: ${{ secrets.AIVEN_PROJECT_NAME_PREFIX }}${{ matrix.aiven_project_name_suffix }}
