name: Unit Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_call:
    inputs:
      ref:
        description: 'The git ref to run checks against'
        required: true
        type: string

permissions:
  contents: read

jobs:
  gatekeeper:
    uses: ./.github/workflows/reusable-gatekeeper.yml

  go_test:
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || inputs.ref }}
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: arduino/setup-task@v2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task test-unit

  opa_validate:
    needs: gatekeeper
    if: needs.gatekeeper.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || inputs.ref }}
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: arduino/setup-task@v2
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: Build and validate bundle
        run: task opa:bundle
