name: Unit Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  go_test:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && !contains(github.event.pull_request.labels.*.name, 'skip workflows')) || github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - uses: arduino/setup-task@v2
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: task test-unit
