// Copyright (c) 2025 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package billinggroup

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/datasource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// datasourceDataModel with specific datasource timeouts
type datasourceDataModel struct {
	dataModel
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

func (obj *datasourceDataModel) DataModel() *dataModel {
	return &obj.dataModel
}

func datasourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"billing_address_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Billing address ID.",
				Validators:          []validator.String{stringvalidator.LengthAtMost(36)},
			},
			"billing_contact_emails": schema.SetAttribute{
				Computed:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "List of billing contact emails.",
			},
			"billing_currency": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Acceptable currencies for a billing group. The possible values are `AUD`, `CAD`, `CHF`, `DKK`, `EUR`, `GBP`, `JPY`, `NOK`, `NZD`, `SEK`, `SGD` and `USD`.",
				Validators:          []validator.String{stringvalidator.OneOf("AUD", "CAD", "CHF", "DKK", "EUR", "GBP", "JPY", "NOK", "NZD", "SEK", "SGD", "USD")},
			},
			"billing_emails": schema.SetAttribute{
				Computed:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "List of billing contact emails.",
			},
			"billing_group_id": schema.StringAttribute{
				MarkdownDescription: "Billing group ID.",
				Required:            true,
			},
			"billing_group_name": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Billing Group Name.",
				Validators:          []validator.String{stringvalidator.LengthAtMost(128)},
			},
			"custom_invoice_text": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Extra billing text.",
				Validators:          []validator.String{stringvalidator.LengthAtMost(254)},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID, a composite of `organization_id` and `billing_group_id` IDs.",
			},
			"organization_id": schema.StringAttribute{
				MarkdownDescription: "ID of an organization.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(36)},
			},
			"payment_method_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Payment method ID.",
			},
			"shipping_address_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Shipping address ID.",
				Validators:          []validator.String{stringvalidator.LengthAtMost(36)},
			},
			"vat_id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "VAT ID.",
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": timeouts.Block(ctx)},
		MarkdownDescription: "Gets information about a billing group. \n\n**This resource is in the beta stage and may change without notice.** Set\nthe `PROVIDER_AIVEN_ENABLE_BETA` environment variable to use the resource.",
	}
}
