// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package billinggroup

import (
	"context"

	avngen "github.com/aiven/go-client-codegen"
	"github.com/aiven/go-client-codegen/handler/organizationbilling"
	"github.com/hashicorp/terraform-plugin-framework/diag"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
	"github.com/aiven/terraform-provider-aiven/internal/plugin/errmsg"
)

var ResourceOptions = adapter.ResourceOptions[*resourceModel, tfModel]{
	Beta:     true,
	Create:   createView,
	Delete:   deleteView,
	IDFields: idFields(),
	Read:     readView,
	Schema:   resourceSchema,
	TypeName: typeName,
	Update:   updateView,
}

var DataSourceOptions = adapter.DataSourceOptions[*datasourceModel, tfModel]{
	Beta:     true,
	Read:     readView,
	Schema:   datasourceSchema,
	TypeName: typeName,
}

func createView(ctx context.Context, client avngen.Client, plan, config *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		var req organizationbilling.OrganizationBillingGroupCreateIn
		diags.Append(expandData(ctx, plan, nil, &req)...)
		if diags.HasError() {
			return
		}

		rsp, err := client.OrganizationBillingGroupCreate(ctx, plan.OrganizationID.ValueString(), &req)
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationBillingGroupCreate Error", err))
			return
		}
		diags.Append(flattenData(ctx, plan, rsp)...)
	}()
	return diags
}

func readView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		rsp, err := client.OrganizationBillingGroupGet(ctx, state.OrganizationID.ValueString(), state.BillingGroupID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationBillingGroupGet Error", err))
			return
		}
		diags.Append(flattenData(ctx, state, rsp)...)
	}()
	return diags
}

func updateView(ctx context.Context, client avngen.Client, plan, state, config *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		var req organizationbilling.OrganizationBillingGroupUpdateIn
		diags.Append(expandData(ctx, plan, state, &req)...)
		if diags.HasError() {
			return
		}

		rsp, err := client.OrganizationBillingGroupUpdate(ctx, state.OrganizationID.ValueString(), state.BillingGroupID.ValueString(), &req)
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationBillingGroupUpdate Error", err))
			return
		}
		diags.Append(flattenData(ctx, plan, rsp)...)
	}()
	return diags
}

func deleteView(ctx context.Context, client avngen.Client, state *tfModel) diag.Diagnostics {
	var diags diag.Diagnostics
	func() {
		err := client.OrganizationBillingGroupDelete(ctx, state.OrganizationID.ValueString(), state.BillingGroupID.ValueString())
		if err != nil {
			diags.Append(errmsg.FromError("OrganizationBillingGroupDelete Error", err))
			return
		}
	}()
	return diags
}
